using System.Data;
using BasaltCore.Native;
using static BasaltCore.Native.StorageInterop;

namespace BasaltCore.SqlServer;

internal static class SqlSchedule
{
    internal static JobDbResult Create(SqlStorageBridge o,ref Schedule schedule,uint firstType,byte[] first,uint secondType,byte[] second){Schedule s=schedule;return o.Safe(()=>{using var db=o.InternalOpen();using var tx=db.BeginTransaction();try{using var c=o.InternalCommand(db,tx,$"INSERT INTO {o.Schema}.[Schedules] VALUES(@i,@j,@t,@e,@z,@n,@m,@c,@a,@b,0,@f,0,@x,@q,@r,1)");Bind(c,s);c.ExecuteNonQuery();o.InternalInsertRecord(db,tx,firstType,s.Id,first);if(secondType!=0)o.InternalInsertRecord(db,tx,secondType,s.Id,second);tx.Commit();return JobDbResult.Ok;}catch{tx.Rollback();throw;}});}
    private static void Bind(System.Data.Common.DbCommand c,Schedule s){SqlStorageBridge.Parameter(c,"@i",SqlStorageBridge.Long(s.Id));SqlStorageBridge.Parameter(c,"@j",SqlStorageBridge.Long(s.JobType));SqlStorageBridge.Parameter(c,"@t",(int)s.Type);SqlStorageBridge.Parameter(c,"@e",s.Enabled!=0);SqlStorageBridge.Parameter(c,"@z",SqlStorageBridge.Long(s.TimezoneReference));SqlStorageBridge.Parameter(c,"@n",SqlStorageBridge.Long(s.Interval));SqlStorageBridge.Parameter(c,"@m",(int)s.IntervalMode);SqlStorageBridge.Parameter(c,"@c",(int)s.CatchUpMax);SqlStorageBridge.Parameter(c,"@a",s.StartAt);SqlStorageBridge.Parameter(c,"@b",s.EndAt);SqlStorageBridge.Parameter(c,"@f",s.NextFireAt);SqlStorageBridge.Parameter(c,"@x",SqlStorageBridge.Long(s.MaxOccurrences));SqlStorageBridge.Parameter(c,"@q",(int)s.MisfirePolicy);SqlStorageBridge.Parameter(c,"@r",(int)s.OverlapPolicy);}
    private static Schedule Read(System.Data.Common.DbDataReader r)=>new(){Id=SqlStorageBridge.ULong(r[0]),JobType=SqlStorageBridge.ULong(r[1]),Type=Convert.ToUInt32(r[2]),Enabled=Convert.ToBoolean(r[3])?1u:0u,TimezoneReference=SqlStorageBridge.ULong(r[4]),Interval=SqlStorageBridge.ULong(r[5]),IntervalMode=Convert.ToUInt32(r[6]),CatchUpMax=Convert.ToUInt32(r[7]),StartAt=Convert.ToInt64(r[8]),EndAt=Convert.ToInt64(r[9]),LastFireAt=Convert.ToInt64(r[10]),NextFireAt=Convert.ToInt64(r[11]),OccurrenceCount=SqlStorageBridge.ULong(r[12]),MaxOccurrences=SqlStorageBridge.ULong(r[13]),MisfirePolicy=Convert.ToUInt32(r[14]),OverlapPolicy=Convert.ToUInt32(r[15]),Revision=SqlStorageBridge.ULong(r[16])};
    internal static JobDbResult Get(SqlStorageBridge o,ulong id,out Schedule schedule){Schedule s=default;var result=o.Safe(()=>{using var db=o.InternalOpen();using var c=o.InternalCommand(db,null,$"SELECT * FROM {o.Schema}.[Schedules] WHERE [ScheduleId]=@i");SqlStorageBridge.Parameter(c,"@i",SqlStorageBridge.Long(id));using var r=c.ExecuteReader();if(!r.Read())return JobDbResult.NotFound;s=Read(r);return JobDbResult.Ok;});schedule=s;return result;}
    internal static JobDbResult Update(SqlStorageBridge o,ref Schedule schedule,ulong revision){Schedule s=schedule;return o.Safe(()=>{using var db=o.InternalOpen();using var c=o.InternalCommand(db,null,$"UPDATE {o.Schema}.[Schedules] SET [Enabled]=@e,[Interval]=@n,[IntervalMode]=@m,[CatchUpMax]=@c,[StartAt]=@a,[EndAt]=@b,[NextFireAt]=@f,[MaxOccurrences]=@x,[MisfirePolicy]=@q,[OverlapPolicy]=@p,[Revision]=[Revision]+1 WHERE [ScheduleId]=@i AND [Revision]=@r");SqlStorageBridge.Parameter(c,"@e",s.Enabled!=0);SqlStorageBridge.Parameter(c,"@n",SqlStorageBridge.Long(s.Interval));SqlStorageBridge.Parameter(c,"@m",(int)s.IntervalMode);SqlStorageBridge.Parameter(c,"@c",(int)s.CatchUpMax);SqlStorageBridge.Parameter(c,"@a",s.StartAt);SqlStorageBridge.Parameter(c,"@b",s.EndAt);SqlStorageBridge.Parameter(c,"@f",s.NextFireAt);SqlStorageBridge.Parameter(c,"@x",SqlStorageBridge.Long(s.MaxOccurrences));SqlStorageBridge.Parameter(c,"@q",(int)s.MisfirePolicy);SqlStorageBridge.Parameter(c,"@p",(int)s.OverlapPolicy);SqlStorageBridge.Parameter(c,"@i",SqlStorageBridge.Long(s.Id));SqlStorageBridge.Parameter(c,"@r",SqlStorageBridge.Long(revision));return c.ExecuteNonQuery()==1?JobDbResult.Ok:JobDbResult.Conflict;});}
    internal static JobDbResult Enabled(SqlStorageBridge o,ulong id,ulong revision,bool enabled)=>o.Safe(()=>{using var db=o.InternalOpen();using var c=o.InternalCommand(db,null,$"UPDATE {o.Schema}.[Schedules] SET [Enabled]=@e,[Revision]=[Revision]+1 WHERE [ScheduleId]=@i AND [Revision]=@r");SqlStorageBridge.Parameter(c,"@e",enabled);SqlStorageBridge.Parameter(c,"@i",SqlStorageBridge.Long(id));SqlStorageBridge.Parameter(c,"@r",SqlStorageBridge.Long(revision));return c.ExecuteNonQuery()==1?JobDbResult.Ok:JobDbResult.Conflict;});
    internal static JobDbResult Remove(SqlStorageBridge o,IntPtr context,ulong id,ulong revision)=>Remove(o,id,revision);
    internal static JobDbResult Remove(SqlStorageBridge o,ulong id,ulong revision)=>o.Safe(()=>{using var db=o.InternalOpen();using var tx=db.BeginTransaction();using var c=o.InternalCommand(db,tx,$"DELETE FROM {o.Schema}.[Schedules] WHERE [ScheduleId]=@i AND [Revision]=@r");SqlStorageBridge.Parameter(c,"@i",SqlStorageBridge.Long(id));SqlStorageBridge.Parameter(c,"@r",SqlStorageBridge.Long(revision));if(c.ExecuteNonQuery()!=1){tx.Rollback();return JobDbResult.Conflict;}using var d=o.InternalCommand(db,tx,$"DELETE FROM {o.Schema}.[Records] WHERE [RecordId]=@i AND [RecordType] IN(101,102)");SqlStorageBridge.Parameter(d,"@i",SqlStorageBridge.Long(id));d.ExecuteNonQuery();tx.Commit();return JobDbResult.Ok;});
    internal static JobDbResult Fire(SqlStorageBridge o,ulong id,ulong revision,long expected,ulong executionId,long fire,long next,uint state)=>o.Safe(()=>{using var db=o.InternalOpen();using var tx=db.BeginTransaction(IsolationLevel.Serializable);try{using var c=o.InternalCommand(db,tx,$"UPDATE {o.Schema}.[Schedules] SET [LastFireAt]=@f,[NextFireAt]=@n,[OccurrenceCount]=[OccurrenceCount]+1,[Revision]=[Revision]+1 WHERE [ScheduleId]=@i AND [Revision]=@r AND [NextFireAt]=@x AND [Enabled]=1");SqlStorageBridge.Parameter(c,"@f",fire);SqlStorageBridge.Parameter(c,"@n",next);SqlStorageBridge.Parameter(c,"@i",SqlStorageBridge.Long(id));SqlStorageBridge.Parameter(c,"@r",SqlStorageBridge.Long(revision));SqlStorageBridge.Parameter(c,"@x",expected);if(c.ExecuteNonQuery()!=1){tx.Rollback();return JobDbResult.Conflict;}using var q=o.InternalCommand(db,tx,$"SELECT [JobDefinitionId] FROM {o.Schema}.[Schedules] WHERE [ScheduleId]=@i");SqlStorageBridge.Parameter(q,"@i",SqlStorageBridge.Long(id));ulong job=SqlStorageBridge.ULong(q.ExecuteScalar()!);var e=new Execution{Id=executionId,JobType=job,ScheduleId=id,State=state,CreatedAt=fire,EligibleAt=fire,MaxAttempts=1,WorkerId=new byte[16]};o.InternalInsertExecution(db,tx,ref e);using var st=o.InternalCommand(db,tx,$"UPDATE {o.Schema}.[Stats] SET [Submitted]=[Submitted]+1,[Revision]=[Revision]+1 WHERE [Id]=1; IF @@ROWCOUNT=0 INSERT INTO {o.Schema}.[Stats] VALUES(1,1,0,0,0,0,0,0,0,1)");st.ExecuteNonQuery();tx.Commit();return JobDbResult.Ok;}catch{tx.Rollback();throw;}});
}
