#include "basalt_abi.h"
#include <string.h>

uint32_t basalt_abi_version(void) { return BASALT_ABI_VERSION; }
jobdb_result_t basalt_db_create(const char *path, jobdb_t **out_db) { return jobdb_create(path, out_db); }
jobdb_result_t basalt_db_open(const char *path, jobdb_t **out_db) { return jobdb_open(path, out_db); }
void basalt_db_close(jobdb_t *db) { jobdb_close(db); }
jobdb_result_t basalt_db_verify(const char *path) { return jobdb_verify(path); }
jobdb_result_t basalt_db_backup(jobdb_t *db, const char *target_path) { return jobdb_backup(db, target_path); }
jobdb_result_t basalt_db_restore(const char *source_path, const char *target_path) { return jobdb_restore(source_path, target_path); }
jobdb_result_t basalt_execution_get(jobdb_t *db, uint64_t id, basalt_execution_view_t *out) { jobdb_execution_t e; jobdb_result_t r; if (!out) return JOBDB_ERR_INVALID_ARGUMENT; r=jobdb_execution_get(db,id,&e); if(r!=JOBDB_OK)return r; out->execution_id=e.execution_id; out->job_definition_id=e.job_definition_id; out->schedule_id=e.schedule_id; out->workflow_id=e.workflow_id; out->state=(uint32_t)e.state; out->payload_version=0; out->created_at=e.created_at; out->eligible_at=e.eligible_at; out->started_at=e.started_at; out->finished_at=e.finished_at; out->priority=e.priority; out->attempt=e.attempt; out->max_attempts=e.max_attempts; out->revision=e.revision; memcpy(out->worker_instance_id,e.worker_instance_id,16); out->lease_expires_at=e.lease_expires_at; out->fencing_token=e.fencing_token; return JOBDB_OK; }
jobdb_result_t basalt_execution_list(jobdb_t *db, uint64_t *ids, size_t capacity, size_t *out_count) { return jobdb_list_record_ids(db, 3, ids, capacity, out_count); }
jobdb_result_t basalt_execution_cancel(jobdb_t *db, uint64_t id, uint64_t expected) { return jobdb_execution_finalize_unleased(db,id,expected,JOBDB_EXEC_CANCELLED,0,0); }
jobdb_result_t basalt_execution_requeue(jobdb_t *db, uint64_t id, uint64_t expected) { jobdb_execution_t e; jobdb_result_t r=jobdb_execution_get(db,id,&e); if(r!=JOBDB_OK)return r; return e.state==JOBDB_EXEC_PAUSED ? jobdb_execution_resume_paused(db,id,expected,NULL) : jobdb_execution_requeue_admin(db,id,expected,NULL); }
jobdb_result_t basalt_ledger_get(jobdb_t *db, uint64_t id, basalt_ledger_view_t *out) { jobdb_ledger_entry_t e; jobdb_result_t r; if (!out) return JOBDB_ERR_INVALID_ARGUMENT; r=jobdb_ledger_get(db,id,&e); if(r!=JOBDB_OK)return r; out->execution_id=e.execution_id;out->job_definition_id=e.job_definition_id;out->schedule_id=e.schedule_id;out->workflow_id=e.workflow_id;out->started_at=e.started_at;out->finished_at=e.finished_at;out->duration=e.duration;out->attempt=e.attempt;out->final_state=(uint32_t)e.final_state;out->result_code=e.result_code;out->error_code=e.error_code;return JOBDB_OK; }
jobdb_result_t basalt_ledger_list(jobdb_t *db, uint64_t *ids, size_t capacity, size_t *out_count) { return jobdb_list_record_ids(db, 4, ids, capacity, out_count); }
jobdb_result_t basalt_stats_get(jobdb_t *db, basalt_stats_view_t *out) { jobdb_stats_t s; jobdb_result_t r;if(!out)return JOBDB_ERR_INVALID_ARGUMENT;r=jobdb_get_stats(db,&s);if(r!=JOBDB_OK)return r;out->submitted_total=s.submitted_total;out->started_total=s.started_total;out->completed_total=s.completed_total;out->failed_total=s.failed_total;out->retried_total=s.retried_total;out->cancelled_total=s.cancelled_total;out->dead_total=s.dead_total;out->recovered_total=s.recovered_total;return JOBDB_OK; }
jobdb_result_t basalt_db_health(jobdb_t *db) { return jobdb_health(db); }
static void schedule_view_from_native(const jobdb_schedule_t *in, basalt_schedule_view_t *out) { out->schedule_id=in->schedule_id;out->job_definition_id=in->job_definition_id;out->schedule_type=in->schedule_type;out->enabled=in->enabled;out->timezone_reference=in->timezone_reference;out->interval=in->interval;out->interval_mode=in->interval_mode;out->catch_up_max=in->catch_up_max;out->start_at=in->start_at;out->end_at=in->end_at;out->last_fire_at=in->last_fire_at;out->next_fire_at=in->next_fire_at;out->occurrence_count=in->occurrence_count;out->max_occurrences=in->max_occurrences;out->misfire_policy=in->misfire_policy;out->overlap_policy=in->overlap_policy;out->revision=in->revision; }
jobdb_result_t basalt_schedule_create(jobcore_t *core,uint64_t id,uint64_t type,uint32_t schedule_type,int64_t first,int64_t interval,uint32_t interval_mode,uint64_t max_occurrences,const void*payload,uint32_t payload_size,uint32_t version,const char*cron,const char*timezone,uint32_t misfire,uint32_t overlap,uint32_t catch_up){jobcore_schedule_spec_t s;memset(&s,0,sizeof s);s.schedule_id=id;s.job_type=type;s.type=(jobcore_schedule_type_t)schedule_type;s.first_fire_at=first;s.interval=interval;s.interval_mode=(jobcore_interval_mode_t)interval_mode;s.max_occurrences=max_occurrences;s.payload=payload;s.payload_size=payload_size;s.payload_version=version;s.cron_expression=cron;s.timezone=timezone;s.misfire_policy=(jobcore_misfire_policy_t)misfire;s.overlap_policy=(jobcore_overlap_policy_t)overlap;s.catch_up_max=catch_up;return jobcore_schedule_create(core,&s);}
jobdb_result_t basalt_schedule_create_v2(jobcore_t *core,uint64_t id,uint64_t type,uint32_t schedule_type,int64_t first,int64_t end,int64_t interval,uint32_t interval_mode,uint64_t max_occurrences,const void*payload,uint32_t payload_size,uint32_t version,const char*cron,const char*timezone,uint32_t misfire,uint32_t overlap,uint32_t catch_up){jobcore_schedule_spec_t s;memset(&s,0,sizeof s);s.schedule_id=id;s.job_type=type;s.type=(jobcore_schedule_type_t)schedule_type;s.first_fire_at=first;s.interval=interval;s.interval_mode=(jobcore_interval_mode_t)interval_mode;s.max_occurrences=max_occurrences;s.payload=payload;s.payload_size=payload_size;s.payload_version=version;s.cron_expression=cron;s.timezone=timezone;s.misfire_policy=(jobcore_misfire_policy_t)misfire;s.overlap_policy=(jobcore_overlap_policy_t)overlap;s.catch_up_max=catch_up;return jobcore_schedule_create_ex(core,&s,end);}
jobdb_result_t basalt_schedule_get(jobcore_t*core,uint64_t id,basalt_schedule_view_t*out){jobdb_schedule_t s;jobdb_result_t r;if(!out)return JOBDB_ERR_INVALID_ARGUMENT;r=jobcore_schedule_get(core,id,&s);if(r==JOBDB_OK)schedule_view_from_native(&s,out);return r;}
jobdb_result_t basalt_schedule_list(jobcore_t*core,uint64_t*ids,size_t capacity,size_t*out_count){basalt_storage_t*storage=jobcore_storage(core);if(!storage)return JOBDB_ERR_INVALID_ARGUMENT;return basalt_storage_list_record_ids(storage,2,ids,capacity,out_count);}
jobdb_result_t basalt_schedule_update(jobcore_t*core,const basalt_schedule_view_t*in,uint64_t expected){jobdb_schedule_t s;if(!in)return JOBDB_ERR_INVALID_ARGUMENT;memset(&s,0,sizeof s);s.schedule_id=in->schedule_id;s.job_definition_id=in->job_definition_id;s.schedule_type=in->schedule_type;s.enabled=in->enabled;s.timezone_reference=in->timezone_reference;s.interval=in->interval;s.interval_mode=in->interval_mode;s.catch_up_max=in->catch_up_max;s.start_at=in->start_at;s.end_at=in->end_at;s.last_fire_at=in->last_fire_at;s.next_fire_at=in->next_fire_at;s.occurrence_count=in->occurrence_count;s.max_occurrences=in->max_occurrences;s.misfire_policy=in->misfire_policy;s.overlap_policy=in->overlap_policy;s.revision=in->revision;return jobcore_schedule_update(core,&s,expected);}
jobdb_result_t basalt_schedule_pause(jobcore_t*core,uint64_t id,uint64_t expected){return jobcore_schedule_pause(core,id,expected);} jobdb_result_t basalt_schedule_resume(jobcore_t*core,uint64_t id,uint64_t expected){return jobcore_schedule_resume(core,id,expected);} jobdb_result_t basalt_schedule_remove(jobcore_t*core,uint64_t id,uint64_t expected){return jobcore_schedule_remove(core,id,expected);}
jobdb_result_t basalt_core_create(jobdb_t *db, uint32_t workers, int64_t lease_duration, jobcore_t **out_core) { return jobcore_create(db, workers, lease_duration, out_core); }
jobdb_result_t basalt_core_create_ex(jobdb_t *db, uint32_t workers, int64_t lease_duration, uint32_t grace_ms, jobcore_t **out_core) { return jobcore_create_ex(db, workers, lease_duration, grace_ms, out_core); }
jobdb_result_t basalt_storage_create_v1(const basalt_storage_vtable_v1 *vtable, void *context, basalt_storage_t **out_storage) { return basalt_storage_create(vtable,context,out_storage); }
void basalt_storage_destroy(basalt_storage_t *storage) { basalt_storage_release(storage); }
jobdb_result_t basalt_core_create_storage_v1(basalt_storage_t *storage,uint32_t workers,int64_t lease_duration,uint32_t grace_ms,jobcore_t **out_core){return jobcore_create_storage_ex(storage,workers,lease_duration,grace_ms,out_core);}
jobdb_result_t basalt_core_worker_id(jobcore_t *core,uint32_t worker_index,uint8_t out_worker_id[16]){return jobcore_worker_id(core,worker_index,out_worker_id);}
void basalt_core_destroy(jobcore_t *core) { jobcore_destroy(core); }
jobdb_result_t basalt_core_start(jobcore_t *core) { return jobcore_start(core); }
jobdb_result_t basalt_core_stop(jobcore_t *core) { return jobcore_stop(core); }
jobdb_result_t basalt_core_register_handler(jobcore_t *core, uint64_t job_type, jobcore_handler_fn handler, void *user_data) { return jobcore_register_handler(core, job_type, handler, user_data); }
jobdb_result_t basalt_core_enqueue(jobcore_t *core, uint64_t job_type, const void *payload, uint32_t payload_size, uint32_t payload_version, int64_t now, uint32_t max_attempts, uint64_t *out_execution_id) { return jobcore_enqueue(core, job_type, payload, payload_size, payload_version, now, max_attempts, out_execution_id); }
jobdb_result_t basalt_core_enqueue_retry(jobcore_t *core, uint64_t job_type, const void *payload, uint32_t payload_size, uint32_t payload_version, int64_t now, const basalt_retry_spec_v1_t *retry, uint64_t *out_execution_id) { jobcore_retry_spec_t r; if(!retry)return JOBDB_ERR_INVALID_ARGUMENT; r.policy=(jobcore_retry_policy_t)retry->policy;r.max_attempts=retry->max_attempts;r.initial_delay=retry->initial_delay;r.max_delay=retry->max_delay;r.backoff_factor=retry->backoff_factor;r.jitter=retry->jitter;return jobcore_enqueue_with_retry(core,job_type,payload,payload_size,payload_version,now,&r,out_execution_id); }
jobdb_result_t basalt_core_enqueue_idempotent(jobcore_t *core, const char *key, uint64_t job_type, const void *payload, uint32_t payload_size, uint32_t payload_version, int64_t now, uint32_t max_attempts, uint64_t *out_execution_id) { return jobcore_enqueue_idempotent(core,key,job_type,payload,payload_size,payload_version,now,max_attempts,out_execution_id); }
jobdb_result_t basalt_core_enqueue_idempotent_retry(jobcore_t *core,const char *key,uint64_t job_type,const void *payload,uint32_t payload_size,uint32_t payload_version,int64_t now,const basalt_retry_spec_v1_t *retry,uint64_t *out_execution_id){jobcore_retry_spec_t r;if(!retry)return JOBDB_ERR_INVALID_ARGUMENT;r.policy=(jobcore_retry_policy_t)retry->policy;r.max_attempts=retry->max_attempts;r.initial_delay=retry->initial_delay;r.max_delay=retry->max_delay;r.backoff_factor=retry->backoff_factor;r.jitter=retry->jitter;return jobcore_enqueue_idempotent_with_retry(core,key,job_type,payload,payload_size,payload_version,now,&r,out_execution_id);}
jobdb_result_t basalt_core_schedule_create(jobcore_t *core, const jobcore_schedule_spec_t *spec) { return jobcore_schedule_create(core, spec); }
jobdb_result_t basalt_core_workflow_submit(jobcore_t *core, uint64_t workflow_id, const basalt_workflow_node_v1_t *nodes, uint32_t count, uint32_t policy, int64_t now) { jobcore_workflow_node_t converted[128]; uint32_t i,j; if(!nodes||count>128)return JOBDB_ERR_INVALID_ARGUMENT;memset(converted,0,sizeof converted);for(i=0;i<count;i++){converted[i].node_id=nodes[i].node_id;converted[i].job_type=nodes[i].job_type;converted[i].payload=nodes[i].payload;converted[i].payload_size=nodes[i].payload_size;converted[i].payload_version=nodes[i].payload_version;converted[i].dependency_count=nodes[i].dependency_count;for(j=0;j<8;j++)converted[i].dependencies[j]=nodes[i].dependencies[j];}return jobcore_workflow_submit(core,workflow_id,converted,count,(jobcore_dependency_policy_t)policy,now); }
jobdb_result_t basalt_workflow_get(jobcore_t *core,uint64_t id,basalt_workflow_status_v1_t*out){jobcore_workflow_status_t s;jobdb_result_t r;if(!out)return JOBDB_ERR_INVALID_ARGUMENT;r=jobcore_workflow_get(core,id,&s);if(r==JOBDB_OK)memcpy(out,&s,sizeof *out);return r;}
jobdb_result_t basalt_workflow_cancel(jobcore_t *core,uint64_t id){return jobcore_workflow_cancel(core,id);}
jobdb_result_t basalt_management_record_create(jobcore_t *core,uint32_t type,uint64_t id,const void *payload,uint32_t size){basalt_storage_t *storage=jobcore_storage(core);if(!storage)return JOBDB_ERR_INVALID_ARGUMENT;return basalt_storage_record_create(storage,type,id,payload,size);}
jobdb_result_t basalt_management_record_upsert(jobcore_t *core,uint32_t type,uint64_t id,const void *payload,uint32_t size){basalt_storage_t *storage=jobcore_storage(core);jobdb_record_t record={0};jobdb_result_t result;if(!storage)return JOBDB_ERR_INVALID_ARGUMENT;result=basalt_storage_record_get(storage,type,id,&record);if(result==JOBDB_ERR_NOT_FOUND)return basalt_storage_record_create(storage,type,id,payload,size);if(result!=JOBDB_OK)return result;result=basalt_storage_record_update(storage,type,id,record.revision,payload,size,NULL);basalt_storage_record_free(storage,&record);return result;}
jobdb_result_t basalt_management_record_update(jobcore_t *core,uint32_t type,uint64_t id,uint64_t revision,const void *payload,uint32_t size){basalt_storage_t *storage=jobcore_storage(core);if(!storage)return JOBDB_ERR_INVALID_ARGUMENT;return basalt_storage_record_update(storage,type,id,revision,payload,size,NULL);}
jobdb_result_t basalt_management_record_get(jobcore_t *core,uint32_t type,uint64_t id,void *payload,uint32_t capacity,uint32_t *out_size){basalt_storage_t *storage=jobcore_storage(core);jobdb_record_t record={0};jobdb_result_t result;if(!storage||!out_size||(capacity&&!payload))return JOBDB_ERR_INVALID_ARGUMENT;result=basalt_storage_record_get(storage,type,id,&record);if(result!=JOBDB_OK)return result;*out_size=record.payload_size;if(record.payload_size>capacity){basalt_storage_record_free(storage,&record);return JOBDB_ERR_LIMIT;}if(record.payload_size)memcpy(payload,record.payload,record.payload_size);basalt_storage_record_free(storage,&record);return JOBDB_OK;}
jobdb_result_t basalt_management_record_list(jobcore_t *core,uint32_t type,uint64_t *ids,size_t capacity,size_t*out_count){basalt_storage_t *storage=jobcore_storage(core);if(!storage)return JOBDB_ERR_INVALID_ARGUMENT;return basalt_storage_list_record_ids(storage,type,ids,capacity,out_count);}
