#include "jobdb.h"
#include "jobdb_codec.h"
#include "jobdb_file.h"
#include "jobdb_lock.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#ifdef _WIN32
#include <windows.h>
#include <io.h>
#include <bcrypt.h>
#pragma comment(lib, "bcrypt.lib")
#else
#include <fcntl.h>
#include <unistd.h>
#endif

#define MANIFEST_SIZE 80u
#define MANIFEST_VERSION 2u
#define WAL_VERSION 1u
#define WAL_HEADER_SIZE 48u
#define WAL_MAGIC "JOBDBWAL"
#define WAL_MAX_PAYLOAD (16u * 1024u * 1024u)
#define RECORD_HEADER_SIZE 68u
#define RECORD_MAGIC "JOBDBREC"
#define EXECUTION_RECORD_TYPE 3u
#define EXECUTION_PAYLOAD_SIZE 120u
#define SCHEDULE_RECORD_TYPE 2u
#define SCHEDULE_PAYLOAD_SIZE 96u
#define STATS_RECORD_TYPE 5u
#define LEDGER_RECORD_TYPE 4u
#define STATS_PAYLOAD_SIZE 64u
#define LEDGER_PAYLOAD_SIZE 80u
static const uint8_t MAGIC[8] = {'J','O','B','D','B','M','A','N'};
struct jobdb { char *path; uint64_t database_id; uint64_t generation; uint64_t last_transaction_id; uint64_t last_checkpoint_transaction; uint64_t next_execution_id; uint32_t feature_flags; jobdb_failure_point_t failure_point; };
typedef enum { TX_PRECONDITION_NONE=0, TX_PRECONDITION_CREATE=1, TX_PRECONDITION_REVISION=2 } tx_precondition_t;
typedef struct tx_op { uint32_t type,target_type; uint64_t target_id,txid; uint64_t expected_revision; tx_precondition_t precondition; uint8_t *payload; uint32_t payload_size; } tx_op_t;
struct jobdb_tx { jobdb_t *db; uint64_t id; int begun; int committed; size_t op_count,op_capacity; tx_op_t *ops; };
static jobdb_result_t wal_recover(jobdb_t *db);
static jobdb_result_t record_read(jobdb_t *db,uint32_t type,uint64_t id,jobdb_record_t*out);
static int fail_now(jobdb_t *db, jobdb_failure_point_t point);
typedef struct { uint32_t type; uint64_t *ids; size_t capacity; size_t count; } record_ids_context_t;
static int collect_record_id(const char *name, void *context) { record_ids_context_t *c=(record_ids_context_t*)context; unsigned type=0; unsigned long long id=0; char extra; if(sscanf(name,"record.%u.%llu%c",&type,&id,&extra)==2&&type==c->type&&id>0){if(c->ids&&c->count<c->capacity)c->ids[c->count]=(uint64_t)id;c->count++;}return 1; }
static jobdb_result_t load_record_ids(jobdb_t *db,uint32_t type,uint64_t **out,size_t *count){size_t n=0;uint64_t *ids=NULL;jobdb_result_t r=jobdb_list_record_ids(db,type,NULL,0,&n);if(r!=JOBDB_OK||n==0){*out=NULL;*count=n;return r;}ids=(uint64_t*)malloc(n*sizeof *ids);if(!ids)return JOBDB_ERR_INTERNAL;r=jobdb_list_record_ids(db,type,ids,n,&n);if(r!=JOBDB_OK){free(ids);return r;}*out=ids;*count=n;return JOBDB_OK;}
typedef struct { jobdb_t *db; jobdb_result_t result; } verify_context_t;
static int verify_record_file(const char *name, void *context) {
    verify_context_t *v=(verify_context_t*)context; unsigned type=0; unsigned long long id=0; char extra;
    if(sscanf(name,"record.%u.%llu%c",&type,&id,&extra)==2&&type>0&&id>0) {
        jobdb_record_t r; v->result=record_read(v->db,type,(uint64_t)id,&r);
        if(v->result==JOBDB_OK) jobdb_record_free(&r); else return 0;
    }
    return 1;
}
static jobdb_result_t verify_records(jobdb_t *db){
    verify_context_t v={db,JOBDB_OK}; jobdb_result_t x=jobdb_visit_files(db->path,verify_record_file,&v);
    return x==JOBDB_ERR_NOT_FOUND?JOBDB_OK:(x==JOBDB_OK?v.result:x);
}
static jobdb_result_t tx_apply(jobdb_tx_t*tx);
static jobdb_result_t record_create_raw(jobdb_t*,uint32_t,uint64_t,const void*,uint32_t);
static jobdb_result_t record_update_raw(jobdb_t*,uint32_t,uint64_t,uint64_t,const void*,uint32_t,uint64_t*);
static jobdb_result_t record_delete_raw(jobdb_t*,uint32_t,uint64_t,uint64_t);
static int worker_valid(const jobdb_worker_id_t*);
static int worker_same(const uint8_t*,const jobdb_worker_id_t*);

static void manifest_encode(uint8_t *b, uint64_t id, uint64_t gen, uint64_t last_tx, uint64_t checkpoint, uint64_t next_exec, uint32_t flags) {
    memset(b, 0, MANIFEST_SIZE); memcpy(b, MAGIC, 8); jobdb_put_u32le(b+8, MANIFEST_VERSION); jobdb_put_u32le(b+12, MANIFEST_SIZE);
    jobdb_put_u64le(b+16,id); jobdb_put_u64le(b+24,gen); jobdb_put_u64le(b+32,last_tx); jobdb_put_u64le(b+40,checkpoint); jobdb_put_u64le(b+48,next_exec); jobdb_put_u32le(b+56,flags); jobdb_put_u32le(b+64,jobdb_crc32c(b,64));
}
static jobdb_result_t manifest_decode(const uint8_t *b, size_t n, uint64_t *id, uint64_t *gen, uint64_t *last_tx, uint64_t *checkpoint, uint64_t *next_exec, uint32_t *flags) {
    if (n != MANIFEST_SIZE) return JOBDB_ERR_CORRUPT;
    if (memcmp(b,MAGIC,8)!=0 || jobdb_get_u32le(b+12)!=MANIFEST_SIZE) return JOBDB_ERR_CORRUPT;
    if (jobdb_get_u32le(b+8)!=MANIFEST_VERSION) return JOBDB_ERR_VERSION;
    if (jobdb_get_u32le(b+64)!=jobdb_crc32c(b,64)) return JOBDB_ERR_CORRUPT;
    *id=jobdb_get_u64le(b+16); *gen=jobdb_get_u64le(b+24); *last_tx=jobdb_get_u64le(b+32); *checkpoint=jobdb_get_u64le(b+40); *next_exec=jobdb_get_u64le(b+48); *flags=jobdb_get_u32le(b+56); if (*id==0) return JOBDB_ERR_CORRUPT; return JOBDB_OK;
}
static void manifest_path(char *out,size_t cap,const char *path,unsigned slot){ (void)snprintf(out,cap,"%s/manifest.%u",path,slot); }
static jobdb_result_t load_manifests(const char *path,uint64_t *id,uint64_t *gen,uint64_t *last_tx,uint64_t *checkpoint,uint64_t *next_exec,uint32_t *flags) {
    uint64_t best_id=0,best_gen=0,best_tx=0,best_cp=0,best_exec=1; uint32_t best_flags=0; int valid=0; jobdb_result_t error=JOBDB_ERR_CORRUPT;
    for(unsigned i=0;i<2;++i){ char p[4096]; uint8_t b[MANIFEST_SIZE]; size_t n=0; uint64_t x=0,g=0,tx=0,cp=0,ex=1;uint32_t fl=0; manifest_path(p,sizeof p,path,i); jobdb_result_t r=jobdb_read_file(p,b,sizeof b,&n); if(r!=JOBDB_OK){error=r;continue;} r=manifest_decode(b,n,&x,&g,&tx,&cp,&ex,&fl); if(r==JOBDB_OK && (!valid || g>best_gen)){best_id=x;best_gen=g;best_tx=tx;best_cp=cp;best_exec=ex;best_flags=fl;valid=1;} else if(r==JOBDB_ERR_VERSION) error=r; }
    if(!valid)return error==JOBDB_ERR_NOT_FOUND?JOBDB_ERR_CORRUPT:error; *id=best_id;*gen=best_gen;*last_tx=best_tx;*checkpoint=best_cp;*next_exec=best_exec;*flags=best_flags;return JOBDB_OK;
}
static char *dupstr(const char *s){ size_t n=strlen(s)+1; char *p=(char*)malloc(n); if(p)memcpy(p,s,n); return p; }
static jobdb_result_t random_id(uint64_t *out) {
    if (!out) return JOBDB_ERR_INVALID_ARGUMENT;
#ifdef _WIN32
    if (BCryptGenRandom(NULL,(PUCHAR)out,(ULONG)sizeof *out,BCRYPT_USE_SYSTEM_PREFERRED_RNG)!=0) return JOBDB_ERR_IO;
#else
    { int fd=open("/dev/urandom",O_RDONLY); ssize_t n=fd<0?-1:read(fd,out,sizeof *out); if(fd>=0)close(fd); if(n!=(ssize_t)sizeof *out)return JOBDB_ERR_IO; }
#endif
    return *out==0?random_id(out):JOBDB_OK;
}
static void wal_path(char *out,size_t cap,const char *path){(void)snprintf(out,cap,"%s/wal.0",path);}
static void record_path(char *out,size_t cap,const char *path,uint32_t type,uint64_t id){(void)snprintf(out,cap,"%s/record.%u.%llu",path,(unsigned)type,(unsigned long long)id);}
static uint32_t record_crc(const uint8_t *b,uint32_t payload_size){uint8_t *x=(uint8_t*)malloc(64u+(size_t)payload_size);if(!x)return 0;memcpy(x,b,64);if(payload_size)memcpy(x+64,b+RECORD_HEADER_SIZE,payload_size);uint32_t c=jobdb_crc32c(x,64u+(size_t)payload_size);free(x);return c;}
static jobdb_result_t record_encode(const jobdb_record_t *r,uint8_t **out,size_t *out_size){
    if(!r||!out||!out_size||r->record_id==0||r->record_type==0||r->payload_size>WAL_MAX_PAYLOAD||(r->payload_size&&!r->payload))return JOBDB_ERR_INVALID_ARGUMENT;
    size_t total=RECORD_HEADER_SIZE+(size_t)r->payload_size;if(total<RECORD_HEADER_SIZE){return JOBDB_ERR_LIMIT;}uint8_t*b=(uint8_t*)calloc(1,total);if(!b)return JOBDB_ERR_INTERNAL;
    memcpy(b,RECORD_MAGIC,8);jobdb_put_u32le(b+8,r->record_type);jobdb_put_u32le(b+12,r->format_version? r->format_version:1);jobdb_put_u32le(b+16,RECORD_HEADER_SIZE);jobdb_put_u32le(b+20,(uint32_t)total);jobdb_put_u64le(b+24,r->record_id);jobdb_put_u64le(b+32,r->generation);jobdb_put_u64le(b+40,r->revision);jobdb_put_u64le(b+48,r->transaction_id);jobdb_put_u32le(b+56,r->flags);jobdb_put_u32le(b+60,r->payload_size);if(r->payload_size)memcpy(b+RECORD_HEADER_SIZE,r->payload,r->payload_size);uint32_t crc=record_crc(b,r->payload_size);if(!crc){free(b);return JOBDB_ERR_INTERNAL;}jobdb_put_u32le(b+64,crc);*out=b;*out_size=total;return JOBDB_OK;
}
static jobdb_result_t record_decode(const uint8_t*b,size_t n,jobdb_record_t*out){if(!b||!out||n<RECORD_HEADER_SIZE||memcmp(b,RECORD_MAGIC,8)!=0||jobdb_get_u32le(b+16)!=RECORD_HEADER_SIZE||jobdb_get_u32le(b+20)!=n)return JOBDB_ERR_CORRUPT;uint32_t ps=jobdb_get_u32le(b+60);if(ps>WAL_MAX_PAYLOAD||n!=RECORD_HEADER_SIZE+(size_t)ps||jobdb_get_u32le(b+64)!=record_crc(b,ps))return JOBDB_ERR_CORRUPT;memset(out,0,sizeof*out);out->record_type=jobdb_get_u32le(b+8);out->format_version=jobdb_get_u32le(b+12);out->record_id=jobdb_get_u64le(b+24);out->generation=jobdb_get_u64le(b+32);out->revision=jobdb_get_u64le(b+40);out->transaction_id=jobdb_get_u64le(b+48);out->flags=jobdb_get_u32le(b+56);out->payload_size=ps;if(ps){out->payload=(uint8_t*)malloc(ps);if(!out->payload)return JOBDB_ERR_INTERNAL;memcpy(out->payload,b+RECORD_HEADER_SIZE,ps);}return JOBDB_OK;}
static jobdb_result_t wal_append(jobdb_t *db, uint32_t type, uint64_t txid, uint32_t target_type, uint64_t target_id, const uint8_t *payload, uint32_t payload_size) {
    uint8_t *b; char path[4096]; FILE *f; size_t total;
    if(db->failure_point==JOBDB_FAILURE_DISK_FULL){db->failure_point=JOBDB_FAILURE_NONE;return JOBDB_ERR_IO;}
    if(type==1 && fail_now(db,JOBDB_FAILURE_BEFORE_WAL_BEGIN))return JOBDB_ERR_IO;
    if (payload_size > WAL_MAX_PAYLOAD || (payload_size != 0 && !payload)) return JOBDB_ERR_LIMIT;
    total = WAL_HEADER_SIZE + (size_t)payload_size + 4u; b=(uint8_t*)calloc(1,total); if(!b)return JOBDB_ERR_INTERNAL;
    memcpy(b,WAL_MAGIC,8); jobdb_put_u32le(b+8,WAL_VERSION); jobdb_put_u32le(b+12,type);
    jobdb_put_u64le(b+16,total); jobdb_put_u64le(b+24,txid); jobdb_put_u32le(b+32,target_type); jobdb_put_u64le(b+36,target_id); jobdb_put_u32le(b+44,payload_size);
    if(payload_size)memcpy(b+WAL_HEADER_SIZE,payload,payload_size);
    jobdb_put_u32le(b+WAL_HEADER_SIZE+payload_size,jobdb_crc32c(b,WAL_HEADER_SIZE+payload_size));
    wal_path(path,sizeof path,db->path); f=fopen(path,"ab"); if(!f){free(b);return JOBDB_ERR_IO;}
    if(fwrite(b,1,total,f)!=total || jobdb_file_sync(f)!=JOBDB_OK || fclose(f)!=0){free(b);return JOBDB_ERR_IO;} free(b); if(type==1&&fail_now(db,JOBDB_FAILURE_AFTER_WAL_BEGIN))return JOBDB_ERR_IO; if((type==2||type==3)&&fail_now(db,JOBDB_FAILURE_AFTER_WAL_OPERATIONS))return JOBDB_ERR_IO; if(type==4&&(fail_now(db,JOBDB_FAILURE_AFTER_COMMIT_WRITE)||fail_now(db,JOBDB_FAILURE_AFTER_COMMIT_SYNC)))return JOBDB_ERR_IO; return JOBDB_OK;
}
static jobdb_result_t record_write(jobdb_t *db,const jobdb_record_t*r){uint8_t*b=NULL;size_t n=0;char p[4096],tmp[4096];if(db->failure_point==JOBDB_FAILURE_DISK_FULL){db->failure_point=JOBDB_FAILURE_NONE;return JOBDB_ERR_IO;}if(fail_now(db,JOBDB_FAILURE_DURING_APPLY))return JOBDB_ERR_IO;jobdb_result_t x=record_encode(r,&b,&n);if(x!=JOBDB_OK)return x;record_path(p,sizeof p,db->path,r->record_type,r->record_id);(void)snprintf(tmp,sizeof tmp,"%s.tmp.%llu",p,(unsigned long long)r->transaction_id);x=jobdb_write_file(tmp,b,n);free(b);if(x!=JOBDB_OK)return x;
#ifdef _WIN32
    if(!MoveFileExA(tmp,p,MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)){remove(tmp);return JOBDB_ERR_IO;}
#else
    if(rename(tmp,p)!=0){remove(tmp);return JOBDB_ERR_IO;} x=jobdb_sync_directory(db->path); if(x!=JOBDB_OK)return x;
#endif
    return JOBDB_OK;}
static jobdb_result_t record_read(jobdb_t*db,uint32_t type,uint64_t id,jobdb_record_t*out){char p[4096];FILE*f;long len;uint8_t*b;size_t n;record_path(p,sizeof p,db->path,type,id);f=fopen(p,"rb");if(!f)return JOBDB_ERR_NOT_FOUND;if(fseek(f,0,SEEK_END)!=0){fclose(f);return JOBDB_ERR_IO;}len=ftell(f);if(len<0||len>(long)(RECORD_HEADER_SIZE+WAL_MAX_PAYLOAD)){fclose(f);return JOBDB_ERR_CORRUPT;}if(fseek(f,0,SEEK_SET)!=0){fclose(f);return JOBDB_ERR_IO;}n=(size_t)len;b=(uint8_t*)malloc(n?n:1);if(!b){fclose(f);return JOBDB_ERR_INTERNAL;}if(fread(b,1,n,f)!=n){free(b);fclose(f);return JOBDB_ERR_IO;}fclose(f);jobdb_result_t x=record_decode(b,n,out);free(b);return x;}
static void execution_encode(const jobdb_execution_t*e,uint8_t*b){memset(b,0,EXECUTION_PAYLOAD_SIZE);jobdb_put_u64le(b,e->execution_id);jobdb_put_u64le(b+8,e->job_definition_id);jobdb_put_u64le(b+16,e->schedule_id);jobdb_put_u64le(b+24,e->workflow_id);jobdb_put_u32le(b+32,(uint32_t)e->state);jobdb_put_u64le(b+36,(uint64_t)e->created_at);jobdb_put_u64le(b+44,(uint64_t)e->eligible_at);jobdb_put_u64le(b+52,(uint64_t)e->started_at);jobdb_put_u64le(b+60,(uint64_t)e->finished_at);jobdb_put_u32le(b+68,(uint32_t)e->priority);jobdb_put_u32le(b+72,e->attempt);jobdb_put_u32le(b+76,e->max_attempts);jobdb_put_u64le(b+80,e->revision);memcpy(b+88,e->worker_instance_id,16);jobdb_put_u64le(b+104,(uint64_t)e->lease_expires_at);jobdb_put_u64le(b+112,e->fencing_token);}
static jobdb_result_t execution_decode(const jobdb_record_t*r,jobdb_execution_t*e){if(!r||!e||r->record_type!=EXECUTION_RECORD_TYPE||r->payload_size!=EXECUTION_PAYLOAD_SIZE)return JOBDB_ERR_CORRUPT;const uint8_t*b=r->payload;memset(e,0,sizeof*e);e->execution_id=jobdb_get_u64le(b);e->job_definition_id=jobdb_get_u64le(b+8);e->schedule_id=jobdb_get_u64le(b+16);e->workflow_id=jobdb_get_u64le(b+24);e->state=(jobdb_execution_state_t)jobdb_get_u32le(b+32);e->created_at=(int64_t)jobdb_get_u64le(b+36);e->eligible_at=(int64_t)jobdb_get_u64le(b+44);e->started_at=(int64_t)jobdb_get_u64le(b+52);e->finished_at=(int64_t)jobdb_get_u64le(b+60);e->priority=(int32_t)jobdb_get_u32le(b+68);e->attempt=jobdb_get_u32le(b+72);e->max_attempts=jobdb_get_u32le(b+76);e->revision=jobdb_get_u64le(b+80);memcpy(e->worker_instance_id,b+88,16);e->lease_expires_at=(int64_t)jobdb_get_u64le(b+104);e->fencing_token=jobdb_get_u64le(b+112);return e->execution_id&&e->state<12?JOBDB_OK:JOBDB_ERR_CORRUPT;}
static void schedule_encode(const jobdb_schedule_t*s,uint8_t*b){memset(b,0,SCHEDULE_PAYLOAD_SIZE);jobdb_put_u64le(b,s->schedule_id);jobdb_put_u64le(b+8,s->job_definition_id);jobdb_put_u32le(b+16,s->schedule_type);jobdb_put_u32le(b+20,s->enabled);jobdb_put_u64le(b+24,s->timezone_reference);jobdb_put_u64le(b+32,(uint64_t)s->start_at);jobdb_put_u64le(b+40,(uint64_t)s->end_at);jobdb_put_u64le(b+48,(uint64_t)s->last_fire_at);jobdb_put_u64le(b+56,(uint64_t)s->next_fire_at);jobdb_put_u64le(b+64,s->occurrence_count);jobdb_put_u64le(b+72,s->max_occurrences);jobdb_put_u32le(b+80,s->misfire_policy);jobdb_put_u32le(b+84,s->overlap_policy);jobdb_put_u64le(b+88,s->revision);}
static jobdb_result_t schedule_decode(const jobdb_record_t*r,jobdb_schedule_t*s){if(!r||!s||r->record_type!=SCHEDULE_RECORD_TYPE||r->payload_size!=SCHEDULE_PAYLOAD_SIZE)return JOBDB_ERR_CORRUPT;const uint8_t*b=r->payload;memset(s,0,sizeof*s);s->schedule_id=jobdb_get_u64le(b);s->job_definition_id=jobdb_get_u64le(b+8);s->schedule_type=jobdb_get_u32le(b+16);s->enabled=jobdb_get_u32le(b+20);s->timezone_reference=jobdb_get_u64le(b+24);s->start_at=(int64_t)jobdb_get_u64le(b+32);s->end_at=(int64_t)jobdb_get_u64le(b+40);s->last_fire_at=(int64_t)jobdb_get_u64le(b+48);s->next_fire_at=(int64_t)jobdb_get_u64le(b+56);s->occurrence_count=jobdb_get_u64le(b+64);s->max_occurrences=jobdb_get_u64le(b+72);s->misfire_policy=jobdb_get_u32le(b+80);s->overlap_policy=jobdb_get_u32le(b+84);s->revision=jobdb_get_u64le(b+88);return s->schedule_id&&s->job_definition_id?JOBDB_OK:JOBDB_ERR_CORRUPT;}
static void stats_encode(const jobdb_stats_t*s,uint8_t*b){const uint64_t v[8]={s->submitted_total,s->started_total,s->completed_total,s->failed_total,s->retried_total,s->cancelled_total,s->dead_total,s->recovered_total};memset(b,0,STATS_PAYLOAD_SIZE);for(unsigned i=0;i<8;i++)jobdb_put_u64le(b+8*i,v[i]);}
static void stats_decode(const uint8_t*b,jobdb_stats_t*s){s->submitted_total=jobdb_get_u64le(b);s->started_total=jobdb_get_u64le(b+8);s->completed_total=jobdb_get_u64le(b+16);s->failed_total=jobdb_get_u64le(b+24);s->retried_total=jobdb_get_u64le(b+32);s->cancelled_total=jobdb_get_u64le(b+40);s->dead_total=jobdb_get_u64le(b+48);s->recovered_total=jobdb_get_u64le(b+56);}
static jobdb_result_t stats_store(jobdb_t*db,const jobdb_stats_t*s){uint8_t p[STATS_PAYLOAD_SIZE];stats_encode(s,p);jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,STATS_RECORD_TYPE,1,&r);if(x==JOBDB_ERR_NOT_FOUND)return record_create_raw(db,STATS_RECORD_TYPE,1,p,sizeof p);if(x!=JOBDB_OK)return x;uint64_t rev=r.revision;jobdb_record_free(&r);return record_update_raw(db,STATS_RECORD_TYPE,1,rev,p,sizeof p,NULL);}
static jobdb_result_t stats_add_submitted(jobdb_t*db){jobdb_stats_t s;jobdb_result_t x=jobdb_get_stats(db,&s);if(x!=JOBDB_OK)return x;s.submitted_total++;return stats_store(db,&s);}
static jobdb_result_t stats_add_completed(jobdb_t*db){jobdb_stats_t s;jobdb_result_t x=jobdb_get_stats(db,&s);if(x!=JOBDB_OK)return x;s.completed_total++;return stats_store(db,&s);}
static jobdb_result_t execution_create_locked(jobdb_t*db,const jobdb_execution_t*e){uint8_t p[EXECUTION_PAYLOAD_SIZE],sp[STATS_PAYLOAD_SIZE];jobdb_execution_t x=*e;jobdb_stats_t stats;jobdb_result_t r;if(!db||!e||!e->execution_id)return JOBDB_ERR_INVALID_ARGUMENT;x.revision=1;execution_encode(&x,p);r=record_create_raw(db,EXECUTION_RECORD_TYPE,e->execution_id,p,sizeof p);if(r!=JOBDB_OK)return r;r=jobdb_get_stats(db,&stats);if(r!=JOBDB_OK)return r;stats.submitted_total++;stats_encode(&stats,sp);{jobdb_record_t old;r=jobdb_record_get(db,STATS_RECORD_TYPE,1,&old);if(r==JOBDB_ERR_NOT_FOUND)return record_create_raw(db,STATS_RECORD_TYPE,1,sp,sizeof sp);if(r!=JOBDB_OK)return r;{uint64_t rev=old.revision;jobdb_record_free(&old);return record_update_raw(db,STATS_RECORD_TYPE,1,rev,sp,sizeof sp,NULL);}}}
int jobdb_execution_transition_allowed(jobdb_execution_state_t from,jobdb_execution_state_t to){static const unsigned char m[12][12]={{0,1,1,0,0,0,0,0,0,0,1,1},{0,0,1,0,0,0,0,0,0,0,1,1},{0,0,0,1,0,0,0,0,0,0,1,1},{0,0,0,0,1,0,0,0,1,0,1,1},{0,0,0,0,0,1,0,1,1,0,1,0},{0,0,1,0,0,0,1,0,0,1,1,0},{0,0,1,0,0,0,0,0,0,0,1,1},{0},{0},{0},{0},{0,0,1,0,0,0,0,0,0,0,0,0}};return from<12&&to<12&&m[from][to]!=0;}
jobdb_result_t jobdb_execution_validate_transition(jobdb_execution_state_t from,jobdb_execution_state_t to){return jobdb_execution_transition_allowed(from,to)?JOBDB_OK:JOBDB_ERR_INVALID_STATE;}
jobdb_result_t jobdb_execution_create(jobdb_t*db,const jobdb_execution_t*e){if(!db||!e||!e->execution_id||e->state>=12)return JOBDB_ERR_INVALID_ARGUMENT;uint8_t p[EXECUTION_PAYLOAD_SIZE],sp[STATS_PAYLOAD_SIZE];jobdb_execution_t x=*e;x.revision=1;execution_encode(&x,p);jobdb_stats_t stats;jobdb_record_t sr={0};jobdb_tx_t*tx=NULL;jobdb_result_t r=jobdb_get_stats(db,&stats);if(r!=JOBDB_OK)return r;stats.submitted_total++;stats_encode(&stats,sp);r=jobdb_tx_begin(db,&tx);if(r!=JOBDB_OK)return r;r=jobdb_tx_put(tx,EXECUTION_RECORD_TYPE,e->execution_id,p,sizeof p);if(r==JOBDB_OK){tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_CREATE;r=jobdb_record_get(db,STATS_RECORD_TYPE,1,&sr);if(r==JOBDB_ERR_NOT_FOUND){r=jobdb_tx_put(tx,STATS_RECORD_TYPE,1,sp,sizeof sp);if(r==JOBDB_OK)tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_CREATE;}else if(r==JOBDB_OK){uint64_t rev=sr.revision;jobdb_record_free(&sr);r=jobdb_tx_put(tx,STATS_RECORD_TYPE,1,sp,sizeof sp);if(r==JOBDB_OK){tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_REVISION;tx->ops[tx->op_count-1].expected_revision=rev;}}}if(r==JOBDB_OK)r=jobdb_tx_commit(tx);jobdb_tx_rollback(tx);return r;}
jobdb_result_t jobdb_execution_get(jobdb_t*db,uint64_t id,jobdb_execution_t*out){if(!db||!id||!out)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,EXECUTION_RECORD_TYPE,id,&r);if(x!=JOBDB_OK)return x;x=execution_decode(&r,out);jobdb_record_free(&r);return x;}
jobdb_result_t jobdb_execution_transition(jobdb_t*db,uint64_t id,uint64_t expected,jobdb_execution_state_t ns,uint64_t*out_revision){if(!db||!id||ns>=12)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_execution_t e;jobdb_result_t x=jobdb_execution_get(db,id,&e);if(x!=JOBDB_OK)return x;if(e.revision!=expected)return JOBDB_ERR_CONFLICT;x=jobdb_execution_validate_transition(e.state,ns);if(x!=JOBDB_OK)return x;e.state=ns;if(ns==JOBDB_EXEC_RUNNING&&e.started_at==0)e.started_at=(int64_t)time(NULL);if(ns==JOBDB_EXEC_FAILED||ns==JOBDB_EXEC_DEAD||ns==JOBDB_EXEC_CANCELLED)e.finished_at=(int64_t)time(NULL);uint8_t p[EXECUTION_PAYLOAD_SIZE];jobdb_execution_t old=e;old.revision=expected+1;execution_encode(&old,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,expected,p,sizeof p,out_revision);return x;}
jobdb_result_t jobdb_execution_start(jobdb_t*db,uint64_t id,const jobdb_worker_id_t*w,uint64_t token,int64_t now,uint64_t*out_revision){jobdb_lock_t*l=NULL;jobdb_execution_t e;jobdb_result_t x;if(!db||!id||!worker_valid(w)||!token||now<0)return JOBDB_ERR_INVALID_ARGUMENT;x=jobdb_lock_acquire(db,5000,&l);if(x!=JOBDB_OK)return x;x=jobdb_execution_get(db,id,&e);if(x==JOBDB_OK&&(!worker_same(e.worker_instance_id,w)||e.fencing_token!=token||e.state!=JOBDB_EXEC_LEASED||e.lease_expires_at<=now))x=JOBDB_ERR_STALE_LEASE;if(x==JOBDB_OK){if(e.started_at==0)e.started_at=now;e.state=JOBDB_EXEC_RUNNING;e.revision++;uint8_t p[EXECUTION_PAYLOAD_SIZE];execution_encode(&e,p);x=record_update_raw(db,EXECUTION_RECORD_TYPE,id,e.revision-1,p,sizeof p,out_revision);}jobdb_lock_release(l);return x;}
static int worker_valid(const jobdb_worker_id_t*w){if(!w)return 0;for(unsigned i=0;i<16;i++)if(w->bytes[i])return 1;return 0;}
static int worker_same(const uint8_t*a,const jobdb_worker_id_t*b){return memcmp(a,b->bytes,16)==0;}
#define jobdb_record_update record_update_raw
#define jobdb_record_create record_create_raw
#define jobdb_record_delete record_delete_raw
#define jobdb_lock_acquire(db, timeout_ms, out) jobdb_lock_acquire_impl((db), (db)->path, 5000, (out))
jobdb_result_t jobdb_claim_next(jobdb_t*db,const jobdb_worker_id_t*w,int64_t now,int64_t duration,jobdb_execution_t*out){uint64_t*ids=NULL,best=0;size_t n=0,i;jobdb_result_t x;if(!db||!worker_valid(w)||!out||duration<=0)return JOBDB_ERR_INVALID_ARGUMENT;{jobdb_lock_t*l=NULL;x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;x=load_record_ids(db,EXECUTION_RECORD_TYPE,&ids,&n);if(x==JOBDB_OK){jobdb_execution_t candidate,best_e={0};int have=0;for(i=0;i<n;i++)if(jobdb_execution_get(db,ids[i],&candidate)==JOBDB_OK&&candidate.state==JOBDB_EXEC_READY&&candidate.eligible_at<=now&&(!have||candidate.priority>best_e.priority||(candidate.priority==best_e.priority&&(candidate.eligible_at<best_e.eligible_at||(candidate.eligible_at==best_e.eligible_at&&candidate.execution_id<best_e.execution_id))))){best=ids[i];best_e=candidate;have=1;}if(!have)x=JOBDB_ERR_NOT_FOUND;else{uint64_t rev=best_e.revision;best_e.state=JOBDB_EXEC_LEASED;memcpy(best_e.worker_instance_id,w->bytes,16);best_e.lease_expires_at=now+duration;best_e.fencing_token++;best_e.revision=rev+1;uint8_t p[EXECUTION_PAYLOAD_SIZE];execution_encode(&best_e,p);x=record_update_raw(db,EXECUTION_RECORD_TYPE,best,rev,p,sizeof p,&rev);if(x==JOBDB_OK){best_e.revision=rev;*out=best_e;}}}free(ids);jobdb_lock_release(l);}return x;}
jobdb_result_t jobdb_renew_lease(jobdb_t*db,uint64_t id,const jobdb_worker_id_t*w,uint64_t token,int64_t expires){if(!db||!worker_valid(w)||!id||expires<=0)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;jobdb_execution_t e;x=jobdb_execution_get(db,id,&e);if(x==JOBDB_OK&&(!worker_same(e.worker_instance_id,w)||e.fencing_token!=token||(e.state!=JOBDB_EXEC_LEASED&&e.state!=JOBDB_EXEC_RUNNING)))x=JOBDB_ERR_STALE_LEASE;if(x==JOBDB_OK){e.lease_expires_at=expires;uint8_t p[EXECUTION_PAYLOAD_SIZE];uint64_t old=e.revision;e.revision=old+1;execution_encode(&e,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,old,p,sizeof p,NULL);}jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_execution_complete(jobdb_t*db,uint64_t id,const jobdb_worker_id_t*w,uint64_t token){if(!db||!worker_valid(w)||!id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;jobdb_execution_t e;x=jobdb_execution_get(db,id,&e);if(x==JOBDB_OK&&(!worker_same(e.worker_instance_id,w)||e.fencing_token!=token||e.state!=JOBDB_EXEC_RUNNING))x=JOBDB_ERR_STALE_LEASE;if(x==JOBDB_OK){e.state=JOBDB_EXEC_DONE;e.finished_at=(int64_t)time(NULL);uint8_t p[EXECUTION_PAYLOAD_SIZE];uint64_t old=e.revision;e.revision=old+1;execution_encode(&e,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,old,p,sizeof p,NULL);if(x==JOBDB_OK)x=stats_add_completed(db);}jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_execution_retry(jobdb_t*db,uint64_t id,const jobdb_worker_id_t*w,uint64_t token,int64_t eligible_at,uint64_t*out_revision){if(!db||!worker_valid(w)||!id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;jobdb_execution_t e;x=jobdb_execution_get(db,id,&e);if(x==JOBDB_OK&&(!worker_same(e.worker_instance_id,w)||e.fencing_token!=token||e.state!=JOBDB_EXEC_RUNNING))x=JOBDB_ERR_STALE_LEASE;if(x==JOBDB_OK){e.state=JOBDB_EXEC_READY;e.attempt++;e.eligible_at=eligible_at;memset(e.worker_instance_id,0,sizeof e.worker_instance_id);e.lease_expires_at=0;uint8_t p[EXECUTION_PAYLOAD_SIZE];uint64_t old=e.revision;e.revision=old+1;execution_encode(&e,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,old,p,sizeof p,out_revision);}jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_reclaim_expired(jobdb_t*db,int64_t now,uint32_t*out_count){uint64_t*ids=NULL;size_t n=0,i;if(!db||!out_count)return JOBDB_ERR_INVALID_ARGUMENT;*out_count=0;jobdb_result_t x=load_record_ids(db,EXECUTION_RECORD_TYPE,&ids,&n);if(x!=JOBDB_OK){free(ids);return x;}for(i=0;i<n;i++){uint64_t id=ids[i];jobdb_execution_t e;jobdb_stats_t stats;jobdb_record_t sr={0};jobdb_tx_t*tx=NULL;uint8_t ep[EXECUTION_PAYLOAD_SIZE],sp[STATS_PAYLOAD_SIZE];if(jobdb_execution_get(db,id,&e)!=JOBDB_OK||(e.state!=JOBDB_EXEC_LEASED&&e.state!=JOBDB_EXEC_RUNNING)||e.lease_expires_at>now)continue;uint64_t old=e.revision;e.state=JOBDB_EXEC_READY;memset(e.worker_instance_id,0,sizeof e.worker_instance_id);e.lease_expires_at=0;e.revision=old+1;execution_encode(&e,ep);if(jobdb_get_stats(db,&stats)!=JOBDB_OK)continue;stats.recovered_total++;stats_encode(&stats,sp);x=jobdb_tx_begin(db,&tx);if(x!=JOBDB_OK)break;x=jobdb_tx_put(tx,EXECUTION_RECORD_TYPE,id,ep,sizeof ep);if(x==JOBDB_OK){tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_REVISION;tx->ops[tx->op_count-1].expected_revision=old;}if(x==JOBDB_OK){x=jobdb_record_get(db,STATS_RECORD_TYPE,1,&sr);if(x==JOBDB_ERR_NOT_FOUND){x=jobdb_tx_put(tx,STATS_RECORD_TYPE,1,sp,sizeof sp);if(x==JOBDB_OK)tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_CREATE;}else if(x==JOBDB_OK){uint64_t srev=sr.revision;jobdb_record_free(&sr);x=jobdb_tx_put(tx,STATS_RECORD_TYPE,1,sp,sizeof sp);if(x==JOBDB_OK){tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_REVISION;tx->ops[tx->op_count-1].expected_revision=srev;}}}if(x==JOBDB_OK)x=jobdb_tx_commit(tx);jobdb_tx_rollback(tx);if(x==JOBDB_OK)(*out_count)++;else if(x==JOBDB_ERR_CONFLICT)continue;else break;}free(ids);return x;}
jobdb_result_t jobdb_schedule_create(jobdb_t*db,const jobdb_schedule_t*s){if(!db||!s||!s->schedule_id||!s->job_definition_id||s->enabled>1)return JOBDB_ERR_INVALID_ARGUMENT;uint8_t p[SCHEDULE_PAYLOAD_SIZE];jobdb_schedule_t x=*s;x.revision=1;schedule_encode(&x,p);return jobdb_record_create(db,SCHEDULE_RECORD_TYPE,s->schedule_id,p,sizeof p);}
jobdb_result_t jobdb_schedule_get(jobdb_t*db,uint64_t id,jobdb_schedule_t*out){if(!db||!id||!out)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,SCHEDULE_RECORD_TYPE,id,&r);if(x!=JOBDB_OK)return x;x=schedule_decode(&r,out);jobdb_record_free(&r);return x;}
jobdb_result_t jobdb_schedule_try_fire(jobdb_t*db,uint64_t sid,uint64_t expected,int64_t expected_next,uint64_t execution_id,int64_t fire_at,int64_t next){if(!db||!sid||!execution_id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;jobdb_schedule_t s;x=jobdb_schedule_get(db,sid,&s);if(x!=JOBDB_OK)goto done;if(!s.enabled||s.revision!=expected||s.next_fire_at!=expected_next){x=JOBDB_ERR_CONFLICT;goto done;}jobdb_execution_t e={0};e.execution_id=execution_id;e.job_definition_id=s.job_definition_id;e.schedule_id=sid;e.state=JOBDB_EXEC_READY;e.created_at=fire_at;e.eligible_at=fire_at;x=execution_create_locked(db,&e);if(x!=JOBDB_OK)goto done;s.last_fire_at=fire_at;s.next_fire_at=next;s.occurrence_count++;s.revision++;uint8_t p[SCHEDULE_PAYLOAD_SIZE];schedule_encode(&s,p);x=record_update_raw(db,SCHEDULE_RECORD_TYPE,sid,expected,p,sizeof p,NULL);done:jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_get_stats(jobdb_t*db,jobdb_stats_t*out){if(!db||!out)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,STATS_RECORD_TYPE,1,&r);if(x==JOBDB_ERR_NOT_FOUND){memset(out,0,sizeof*out);return JOBDB_OK;}if(x!=JOBDB_OK)return x;if(r.payload_size!=STATS_PAYLOAD_SIZE){jobdb_record_free(&r);return JOBDB_ERR_CORRUPT;}stats_decode(r.payload,out);jobdb_record_free(&r);return JOBDB_OK;}
static void ledger_encode(const jobdb_ledger_entry_t*e,uint8_t*b){memset(b,0,LEDGER_PAYLOAD_SIZE);jobdb_put_u64le(b,e->execution_id);jobdb_put_u64le(b+8,e->job_definition_id);jobdb_put_u64le(b+16,e->schedule_id);jobdb_put_u64le(b+24,e->workflow_id);jobdb_put_u64le(b+32,(uint64_t)e->started_at);jobdb_put_u64le(b+40,(uint64_t)e->finished_at);jobdb_put_u32le(b+48,e->attempt);jobdb_put_u32le(b+52,(uint32_t)e->final_state);jobdb_put_u64le(b+56,(uint64_t)e->duration);jobdb_put_u32le(b+64,(uint32_t)e->result_code);jobdb_put_u32le(b+68,(uint32_t)e->error_code);}
static jobdb_result_t ledger_decode(const jobdb_record_t*r,jobdb_ledger_entry_t*e){if(!r||r->payload_size!=LEDGER_PAYLOAD_SIZE)return JOBDB_ERR_CORRUPT;const uint8_t*b=r->payload;memset(e,0,sizeof*e);e->execution_id=jobdb_get_u64le(b);e->job_definition_id=jobdb_get_u64le(b+8);e->schedule_id=jobdb_get_u64le(b+16);e->workflow_id=jobdb_get_u64le(b+24);e->started_at=(int64_t)jobdb_get_u64le(b+32);e->finished_at=(int64_t)jobdb_get_u64le(b+40);e->attempt=jobdb_get_u32le(b+48);e->final_state=(jobdb_execution_state_t)jobdb_get_u32le(b+52);e->duration=(int64_t)jobdb_get_u64le(b+56);e->result_code=(int32_t)jobdb_get_u32le(b+64);e->error_code=(int32_t)jobdb_get_u32le(b+68);return e->execution_id&&e->final_state>=JOBDB_EXEC_DONE&&e->final_state<12?JOBDB_OK:JOBDB_ERR_CORRUPT;}
jobdb_result_t jobdb_ledger_append(jobdb_t*db,const jobdb_ledger_entry_t*e){if(!db||!e||!e->execution_id||e->final_state<JOBDB_EXEC_DONE||e->final_state>=12)return JOBDB_ERR_INVALID_ARGUMENT;uint8_t p[LEDGER_PAYLOAD_SIZE];ledger_encode(e,p);return jobdb_record_create(db,LEDGER_RECORD_TYPE,e->execution_id,p,sizeof p);}
jobdb_result_t jobdb_ledger_get(jobdb_t*db,uint64_t id,jobdb_ledger_entry_t*out){if(!db||!id||!out)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,LEDGER_RECORD_TYPE,id,&r);if(x!=JOBDB_OK)return x;x=ledger_decode(&r,out);jobdb_record_free(&r);return x;}
typedef struct retention_item {uint64_t id,revision;int64_t finished_at;} retention_item_t;
static int retention_cmp(const void*a,const void*b){const retention_item_t*x=(const retention_item_t*)a,*y=(const retention_item_t*)b;return x->finished_at<y->finished_at?-1:x->finished_at>y->finished_at?1:0;}
jobdb_result_t jobdb_apply_retention(jobdb_t*db,int64_t now,const jobdb_retention_t*r,uint32_t*out_deleted){if(!db||!r||!out_deleted||r->max_age<0)return JOBDB_ERR_INVALID_ARGUMENT;*out_deleted=0;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;uint64_t*ids=NULL;size_t n=0,i,count=0;x=load_record_ids(db,LEDGER_RECORD_TYPE,&ids,&n);if(x!=JOBDB_OK){jobdb_lock_release(l);return x;}retention_item_t*items=(retention_item_t*)calloc(n?n:1,sizeof*items);if(!items){free(ids);jobdb_lock_release(l);return JOBDB_ERR_INTERNAL;}for(i=0;i<n;i++){jobdb_record_t rec;if(jobdb_record_get(db,LEDGER_RECORD_TYPE,ids[i],&rec)!=JOBDB_OK)continue;jobdb_ledger_entry_t e;if(ledger_decode(&rec,&e)==JOBDB_OK){items[count].id=ids[i];items[count].revision=rec.revision;items[count].finished_at=e.finished_at;count++;}jobdb_record_free(&rec);}qsort(items,count,sizeof*items,retention_cmp);uint64_t keep=count;for(i=0;i<count;i++){int expired=r->max_age>0&&items[i].finished_at>0&&items[i].finished_at<=now-r->max_age;if(expired||((r->max_records>0&&keep>r->max_records))||(r->max_bytes>0&&keep*(uint64_t)(RECORD_HEADER_SIZE+LEDGER_PAYLOAD_SIZE)>r->max_bytes)){if(jobdb_record_delete(db,LEDGER_RECORD_TYPE,items[i].id,items[i].revision)==JOBDB_OK){if(keep)keep--;(*out_deleted)++;}}}free(items);free(ids);jobdb_lock_release(l);return JOBDB_OK;}
jobdb_result_t jobdb_checkpoint(jobdb_t*db){if(!db)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,5000,&l);if(x!=JOBDB_OK)return x;x=wal_recover(db);if(x!=JOBDB_OK){jobdb_lock_release(l);return x;}if(fail_now(db,JOBDB_FAILURE_CHECKPOINT_BEFORE_MANIFEST)){jobdb_lock_release(l);return JOBDB_ERR_IO;}uint8_t b[MANIFEST_SIZE];char p[4096];uint64_t next=db->generation+1;manifest_encode(b,db->database_id,next,db->last_transaction_id,db->last_transaction_id,db->next_execution_id,db->feature_flags);manifest_path(p,sizeof p,db->path,(unsigned)(next&1u));x=jobdb_write_file(p,b,sizeof b);if(x==JOBDB_OK)db->generation=next;if(x==JOBDB_OK&&fail_now(db,JOBDB_FAILURE_CHECKPOINT_AFTER_MANIFEST))x=JOBDB_ERR_IO;if(x==JOBDB_OK&&fail_now(db,JOBDB_FAILURE_BEFORE_WAL_TRUNCATE))x=JOBDB_ERR_IO;if(x==JOBDB_OK){wal_path(p,sizeof p,db->path);x=jobdb_truncate_file(p,0);if(x==JOBDB_OK&&fail_now(db,JOBDB_FAILURE_AFTER_WAL_TRUNCATE))x=JOBDB_ERR_IO;}jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_allocate_execution_id(jobdb_t*db,uint64_t*out_execution_id){jobdb_lock_t*l=NULL;jobdb_result_t r;uint64_t id,g,tx,cp,ex;uint32_t fl;uint8_t b[MANIFEST_SIZE];char p[4096];if(!db||!out_execution_id)return JOBDB_ERR_INVALID_ARGUMENT;r=jobdb_lock_acquire(db,5000,&l);if(r!=JOBDB_OK)return r;r=load_manifests(db->path,&id,&g,&tx,&cp,&ex,&fl);if(r==JOBDB_OK){if(ex==UINT64_MAX)r=JOBDB_ERR_LIMIT;else{*out_execution_id=ex;ex++;g++;manifest_encode(b,id,g,tx,cp,ex,fl);manifest_path(p,sizeof p,db->path,(unsigned)(g&1u));r=jobdb_write_file(p,b,sizeof b);if(r==JOBDB_OK){db->database_id=id;db->generation=g;db->last_transaction_id=tx;db->last_checkpoint_transaction=cp;db->next_execution_id=ex;db->feature_flags=fl;}}}jobdb_lock_release(l);return r;}
jobdb_result_t jobdb_list_record_ids(jobdb_t*db,uint32_t type,uint64_t*ids,size_t capacity,size_t*out_count){record_ids_context_t c;jobdb_result_t r;if(!db||!type||!out_count||(capacity&&!ids))return JOBDB_ERR_INVALID_ARGUMENT;c.type=type;c.ids=ids;c.capacity=capacity;c.count=0;r=jobdb_visit_files(db->path,collect_record_id,&c);if(r!=JOBDB_OK&&r!=JOBDB_ERR_NOT_FOUND)return r;*out_count=c.count;return JOBDB_OK;}
void jobdb_record_free(jobdb_record_t*r){if(r){free(r->payload);memset(r,0,sizeof*r);}}
#undef jobdb_record_update
#undef jobdb_record_create
#undef jobdb_record_delete
#undef jobdb_lock_acquire
static jobdb_result_t record_create_raw(jobdb_t*db,uint32_t type,uint64_t id,const void*payload,uint32_t size){if(!db||!type||!id||(size&&!payload)||size>WAL_MAX_PAYLOAD)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t old;jobdb_result_t x=record_read(db,type,id,&old);if(x==JOBDB_OK){jobdb_record_free(&old);return JOBDB_ERR_ALREADY_EXISTS;}if(x!=JOBDB_ERR_NOT_FOUND)return x;jobdb_record_t r={type,1,id,db->generation,1,0,0,(uint8_t*)payload,size};return record_write(db,&r);}
jobdb_result_t jobdb_record_get(jobdb_t*db,uint32_t type,uint64_t id,jobdb_record_t*out){if(!db||!out||!type||!id)return JOBDB_ERR_INVALID_ARGUMENT;return record_read(db,type,id,out);}
static jobdb_result_t record_update_raw(jobdb_t*db,uint32_t type,uint64_t id,uint64_t expected,const void*payload,uint32_t size,uint64_t*out_revision){if(!db||!type||!id||(size&&!payload)||size>WAL_MAX_PAYLOAD)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=record_read(db,type,id,&r);if(x!=JOBDB_OK)return x;if(r.revision!=expected){jobdb_record_free(&r);return JOBDB_ERR_CONFLICT;}r.revision++;r.generation=db->generation;r.payload=(uint8_t*)payload;r.payload_size=size;x=record_write(db,&r);r.payload=NULL;jobdb_record_free(&r);if(x==JOBDB_OK&&out_revision)*out_revision=expected+1;return x;}
static jobdb_result_t record_delete_raw(jobdb_t*db,uint32_t type,uint64_t id,uint64_t expected){if(!db||!type||!id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=record_read(db,type,id,&r);if(x!=JOBDB_OK)return x;if(r.revision!=expected){jobdb_record_free(&r);return JOBDB_ERR_CONFLICT;}char p[4096];record_path(p,sizeof p,db->path,type,id);jobdb_record_free(&r);return jobdb_remove_file(p);}
jobdb_result_t jobdb_record_create(jobdb_t*db,uint32_t type,uint64_t id,const void*payload,uint32_t size){jobdb_tx_t*tx=NULL;jobdb_result_t r;if(!db||!type||!id||(size&&!payload)||size>WAL_MAX_PAYLOAD)return JOBDB_ERR_INVALID_ARGUMENT;r=jobdb_tx_begin(db,&tx);if(r!=JOBDB_OK)return r;r=jobdb_tx_put(tx,type,id,payload,size);if(r==JOBDB_OK){tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_CREATE;r=jobdb_tx_commit(tx);}jobdb_tx_rollback(tx);return r;}
jobdb_result_t jobdb_record_update(jobdb_t*db,uint32_t type,uint64_t id,uint64_t expected,const void*payload,uint32_t size,uint64_t*out_revision){jobdb_tx_t*tx=NULL;jobdb_result_t r;if(!db||!type||!id||(size&&!payload)||size>WAL_MAX_PAYLOAD)return JOBDB_ERR_INVALID_ARGUMENT;r=jobdb_tx_begin(db,&tx);if(r!=JOBDB_OK)return r;r=jobdb_tx_put(tx,type,id,payload,size);if(r==JOBDB_OK){tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_REVISION;tx->ops[tx->op_count-1].expected_revision=expected;r=jobdb_tx_commit(tx);if(r==JOBDB_OK&&out_revision)*out_revision=expected+1;}jobdb_tx_rollback(tx);return r;}
jobdb_result_t jobdb_record_delete(jobdb_t*db,uint32_t type,uint64_t id,uint64_t expected){jobdb_tx_t*tx=NULL;jobdb_result_t r;if(!db||!type||!id)return JOBDB_ERR_INVALID_ARGUMENT;r=jobdb_tx_begin(db,&tx);if(r!=JOBDB_OK)return r;r=jobdb_tx_delete(tx,type,id);if(r==JOBDB_OK){tx->ops[tx->op_count-1].precondition=TX_PRECONDITION_REVISION;tx->ops[tx->op_count-1].expected_revision=expected;r=jobdb_tx_commit(tx);}jobdb_tx_rollback(tx);return r;}
static int fail_now(jobdb_t *db, jobdb_failure_point_t point){if(db->failure_point==point){db->failure_point=JOBDB_FAILURE_NONE;return 1;}return 0;}
static jobdb_result_t wal_recover(jobdb_t *db) {
    char path[4096]; FILE *f; uint8_t h[WAL_HEADER_SIZE]; size_t n,cap=0,count=0,committed_count=0; uint64_t max_id=0,active=0,tx_start=0,replay_from=db->last_transaction_id; tx_op_t *ops=NULL; int corrupt=0;
    wal_path(path,sizeof path,db->path); f=fopen(path,"rb"); if(!f)return errno==ENOENT?JOBDB_OK:JOBDB_ERR_IO;
    for(;;){ long record_start=ftell(f); uint64_t size;uint32_t payload_size,type;uint8_t *payload=NULL,crc_bytes[4],*check;
        n=fread(h,1,sizeof h,f); if(n==0)break; if(n!=sizeof h){if(ferror(f)){corrupt=1;}else if(jobdb_truncate_file(path,(uint64_t)record_start)!=JOBDB_OK)corrupt=1;break;}
        size=jobdb_get_u64le(h+16);type=jobdb_get_u32le(h+12);payload_size=jobdb_get_u32le(h+44);
        if(memcmp(h,WAL_MAGIC,8)!=0||jobdb_get_u32le(h+8)!=WAL_VERSION||type<1||type>4||size!=(uint64_t)WAL_HEADER_SIZE+payload_size+4u||payload_size>WAL_MAX_PAYLOAD||jobdb_get_u64le(h+24)==0){corrupt=1;break;}
        payload=payload_size?(uint8_t*)malloc(payload_size):NULL;if(payload_size&&!payload){corrupt=1;break;}n=payload_size?fread(payload,1,payload_size,f):0;if(n!=payload_size){free(payload);if(jobdb_truncate_file(path,(uint64_t)record_start)!=JOBDB_OK)corrupt=1;break;}n=fread(crc_bytes,1,4,f);if(n!=4){free(payload);if(jobdb_truncate_file(path,(uint64_t)record_start)!=JOBDB_OK)corrupt=1;break;}
        check=(uint8_t*)malloc(WAL_HEADER_SIZE+(size_t)payload_size);if(!check){free(payload);corrupt=1;break;}memcpy(check,h,WAL_HEADER_SIZE);if(payload_size)memcpy(check+WAL_HEADER_SIZE,payload,payload_size);if(jobdb_get_u32le(crc_bytes)!=jobdb_crc32c(check,WAL_HEADER_SIZE+(size_t)payload_size)){free(check);free(payload);corrupt=1;break;}free(check);
        {uint64_t txid=jobdb_get_u64le(h+24);if(type==1){if(active||count!=0&&ops[count-1].txid==txid){free(payload);corrupt=1;break;}active=txid;tx_start=(uint64_t)record_start;}else if(type==2||type==3){if(!active||txid!=active){free(payload);corrupt=1;break;}if(count==cap){size_t nc=cap?cap*2:16;if(nc>1000000u)nc=1000000u;if(nc<=cap){free(payload);corrupt=1;break;}tx_op_t*no=(tx_op_t*)realloc(ops,nc*sizeof *ops);if(!no){free(payload);corrupt=1;break;}ops=no;cap=nc;}ops[count].type=type;ops[count].target_type=jobdb_get_u32le(h+32);ops[count].target_id=jobdb_get_u64le(h+36);ops[count].txid=txid;ops[count].payload_size=payload_size;ops[count].payload=payload;count++;payload=NULL;}else{if(!active||txid!=active){free(payload);corrupt=1;break;}active=0;committed_count=count;}if(txid>max_id)max_id=txid;}free(payload);
    }
    fclose(f);if(corrupt){for(size_t i=0;i<count;i++)free(ops[i].payload);free(ops);return JOBDB_ERR_CORRUPT;}if(active&&jobdb_truncate_file(path,tx_start)!=JOBDB_OK){for(size_t i=0;i<count;i++)free(ops[i].payload);free(ops);return JOBDB_ERR_IO;}if(active)count=committed_count;if(max_id>db->last_transaction_id)db->last_transaction_id=max_id;
    for(size_t i=0;i<count;i++){if(ops[i].txid<=replay_from)continue;jobdb_tx_t fake={0};tx_op_t one=ops[i];fake.db=db;fake.id=ops[i].txid;fake.op_count=1;fake.ops=&one;if(tx_apply(&fake)!=JOBDB_OK){for(size_t k=0;k<count;k++)free(ops[k].payload);free(ops);return JOBDB_ERR_IO;}}
    for(size_t i=0;i<count;i++)free(ops[i].payload);free(ops);return JOBDB_OK;
}
jobdb_result_t jobdb_create(const char *path, jobdb_t **out_db){
    if(!path||!out_db||!*path){return JOBDB_ERR_INVALID_ARGUMENT;} *out_db=NULL; jobdb_result_t r=jobdb_make_dir(path); if(r!=JOBDB_OK&&r!=JOBDB_ERR_ALREADY_EXISTS)return r;
    char p[4096]; uint8_t b[MANIFEST_SIZE]; uint64_t id=0; if(r==JOBDB_ERR_ALREADY_EXISTS){char m0[4096],m1[4096];manifest_path(m0,sizeof m0,path,0);manifest_path(m1,sizeof m1,path,1);if(jobdb_file_exists(m0)||jobdb_file_exists(m1))return JOBDB_ERR_ALREADY_EXISTS;} r=random_id(&id);if(r!=JOBDB_OK)return r; manifest_encode(b,id,1,0,0,1,0); manifest_path(p,sizeof p,path,0); r=jobdb_write_file(p,b,sizeof b); if(r!=JOBDB_OK)return r; manifest_encode(b,id,2,0,0,1,0); manifest_path(p,sizeof p,path,1); r=jobdb_write_file(p,b,sizeof b); if(r!=JOBDB_OK)return r;
    jobdb_t *db=(jobdb_t*)calloc(1,sizeof *db); if(!db)return JOBDB_ERR_INTERNAL; db->path=dupstr(path); if(!db->path){free(db);return JOBDB_ERR_INTERNAL;}db->database_id=id;db->generation=2;db->next_execution_id=1;*out_db=db;return JOBDB_OK;
}
jobdb_result_t jobdb_open(const char *path, jobdb_t **out_db){ if(!path||!out_db||!*path)return JOBDB_ERR_INVALID_ARGUMENT;*out_db=NULL;uint64_t id=0,g=0,tx=0,cp=0,ex=1;uint32_t fl=0;jobdb_result_t r=load_manifests(path,&id,&g,&tx,&cp,&ex,&fl);if(r!=JOBDB_OK)return r;jobdb_t*db=(jobdb_t*)calloc(1,sizeof*db);if(!db)return JOBDB_ERR_INTERNAL;db->path=dupstr(path);if(!db->path){free(db);return JOBDB_ERR_INTERNAL;}db->database_id=id;db->generation=g;db->last_transaction_id=tx;db->last_checkpoint_transaction=cp;db->next_execution_id=ex;db->feature_flags=fl;jobdb_lock_t*l=NULL;r=jobdb_lock_acquire_impl(db,db->path,5000,&l);if(r==JOBDB_OK){r=wal_recover(db);jobdb_lock_release(l);}if(r!=JOBDB_OK){jobdb_close(db);return r;}*out_db=db;return JOBDB_OK; }
jobdb_result_t jobdb_tx_begin(jobdb_t *db, jobdb_tx_t **out_tx){if(!db||!out_tx)return JOBDB_ERR_INVALID_ARGUMENT;*out_tx=NULL;jobdb_tx_t*tx=(jobdb_tx_t*)calloc(1,sizeof*tx);if(!tx)return JOBDB_ERR_INTERNAL;tx->ops=(tx_op_t*)calloc(8,sizeof*tx->ops);if(!tx->ops){free(tx);return JOBDB_ERR_INTERNAL;}tx->op_capacity=8;tx->db=db;tx->begun=1;if(fail_now(db,JOBDB_FAILURE_AFTER_BEGIN)){free(tx->ops);free(tx);return JOBDB_ERR_IO;}*out_tx=tx;return JOBDB_OK;}
jobdb_result_t jobdb_tx_put(jobdb_tx_t *tx,uint32_t target_type,uint64_t target_id,const void *payload,uint32_t payload_size){tx_op_t*op;if(!tx||!tx->begun||tx->committed||target_type==0||target_id==0||(payload_size&&!payload)||payload_size>WAL_MAX_PAYLOAD)return JOBDB_ERR_INVALID_TRANSACTION;if(tx->op_count==tx->op_capacity){size_t nc=tx->op_capacity*2;tx_op_t*no;if(nc>1000000u)nc=1000000u;if(nc<=tx->op_capacity)return JOBDB_ERR_LIMIT;no=(tx_op_t*)realloc(tx->ops,nc*sizeof*no);if(!no)return JOBDB_ERR_INTERNAL;memset(no+tx->op_capacity,0,(nc-tx->op_capacity)*sizeof*no);tx->ops=no;tx->op_capacity=nc;}op=&tx->ops[tx->op_count++];op->type=2;op->target_type=target_type;op->target_id=target_id;op->payload_size=payload_size;if(payload_size){op->payload=(uint8_t*)malloc(payload_size);if(!op->payload){tx->op_count--;return JOBDB_ERR_INTERNAL;}memcpy(op->payload,payload,payload_size);}if(fail_now(tx->db,JOBDB_FAILURE_AFTER_OPERATION))return JOBDB_ERR_IO;return JOBDB_OK;}
jobdb_result_t jobdb_tx_delete(jobdb_tx_t *tx,uint32_t target_type,uint64_t target_id){if(!tx||!tx->begun||tx->committed||target_type==0||target_id==0)return JOBDB_ERR_INVALID_TRANSACTION;if(tx->op_count==tx->op_capacity){size_t nc=tx->op_capacity*2;tx_op_t*no;if(nc>1000000u)nc=1000000u;if(nc<=tx->op_capacity)return JOBDB_ERR_LIMIT;no=(tx_op_t*)realloc(tx->ops,nc*sizeof*no);if(!no)return JOBDB_ERR_INTERNAL;memset(no+tx->op_capacity,0,(nc-tx->op_capacity)*sizeof*no);tx->ops=no;tx->op_capacity=nc;}tx->ops[tx->op_count].type=3;tx->ops[tx->op_count].target_type=target_type;tx->ops[tx->op_count].target_id=target_id;tx->op_count++;if(fail_now(tx->db,JOBDB_FAILURE_AFTER_OPERATION))return JOBDB_ERR_IO;return JOBDB_OK;}
static jobdb_result_t tx_apply(jobdb_tx_t*tx){for(size_t i=0;i<tx->op_count;i++){tx_op_t*op=&tx->ops[i];char p[4096];record_path(p,sizeof p,tx->db->path,op->target_type,op->target_id);if(op->type==3){if(remove(p)!=0&&errno!=ENOENT)return JOBDB_ERR_IO;continue;}jobdb_record_t old;uint64_t rev=1;jobdb_result_t r=record_read(tx->db,op->target_type,op->target_id,&old);if(r==JOBDB_OK){if(old.transaction_id==tx->id&&old.payload_size==op->payload_size&&(!op->payload_size||memcmp(old.payload,op->payload,op->payload_size)==0)){jobdb_record_free(&old);continue;}rev=old.revision+1;jobdb_record_free(&old);}else if(r!=JOBDB_ERR_NOT_FOUND)return r;jobdb_record_t rec={op->target_type,1,op->target_id,tx->db->generation,rev,tx->id,0,op->payload,op->payload_size};r=record_write(tx->db,&rec);if(r!=JOBDB_OK)return r;}return JOBDB_OK;}
jobdb_result_t jobdb_tx_commit(jobdb_tx_t *tx){jobdb_lock_t*l=NULL;jobdb_result_t r;if(!tx||!tx->begun||tx->committed)return JOBDB_ERR_INVALID_TRANSACTION;if(fail_now(tx->db,JOBDB_FAILURE_BEFORE_COMMIT))return JOBDB_ERR_IO;r=jobdb_lock_acquire(tx->db,5000,&l);if(r!=JOBDB_OK)return r;r=wal_recover(tx->db);if(r==JOBDB_OK){if(tx->db->last_transaction_id==UINT64_MAX)r=JOBDB_ERR_LIMIT;else tx->id=tx->db->last_transaction_id+1;for(size_t i=0;r==JOBDB_OK&&i<tx->op_count;i++){tx_op_t*op=&tx->ops[i];jobdb_record_t old;jobdb_result_t q=record_read(tx->db,op->target_type,op->target_id,&old);if(op->precondition==TX_PRECONDITION_CREATE){if(q==JOBDB_OK){jobdb_record_free(&old);r=JOBDB_ERR_ALREADY_EXISTS;}else if(q!=JOBDB_ERR_NOT_FOUND)r=q;}else if(op->precondition==TX_PRECONDITION_REVISION){if(q!=JOBDB_OK)r=q==JOBDB_ERR_NOT_FOUND?JOBDB_ERR_CONFLICT:q;else{if(old.revision!=op->expected_revision)r=JOBDB_ERR_CONFLICT;jobdb_record_free(&old);}}else if(q==JOBDB_OK)jobdb_record_free(&old);op->txid=tx->id;}if(r==JOBDB_OK)r=wal_append(tx->db,1,tx->id,0,0,NULL,0);for(size_t i=0;r==JOBDB_OK&&i<tx->op_count;i++)r=wal_append(tx->db,tx->ops[i].type,tx->id,tx->ops[i].target_type,tx->ops[i].target_id,tx->ops[i].payload,tx->ops[i].payload_size);if(r==JOBDB_OK)r=wal_append(tx->db,4,tx->id,0,0,NULL,0);if(r==JOBDB_OK)tx->committed=1;if(r==JOBDB_OK&&fail_now(tx->db,JOBDB_FAILURE_AFTER_COMMIT))r=JOBDB_ERR_IO;if(r==JOBDB_OK)r=tx_apply(tx);if(r==JOBDB_OK){tx->db->last_transaction_id=tx->id;uint8_t b[MANIFEST_SIZE];char p[4096];uint64_t g=tx->db->generation+1;manifest_encode(b,tx->db->database_id,g,tx->db->last_transaction_id,tx->db->last_checkpoint_transaction,tx->db->next_execution_id,tx->db->feature_flags);manifest_path(p,sizeof p,tx->db->path,(unsigned)(g&1u));r=jobdb_write_file(p,b,sizeof b);if(r==JOBDB_OK)tx->db->generation=g;}}jobdb_lock_release(l);return r;}
void jobdb_tx_rollback(jobdb_tx_t *tx){if(tx){for(size_t i=0;i<tx->op_count;i++)free(tx->ops[i].payload);free(tx->ops);free(tx);}}
void jobdb_test_fail_next(jobdb_t *db, jobdb_failure_point_t point){if(db)db->failure_point=point;}
jobdb_result_t jobdb_verify(const char *path){uint64_t id=0,g=0,tx=0,cp=0,ex=1;uint32_t fl=0;if(!path)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_result_t x=load_manifests(path,&id,&g,&tx,&cp,&ex,&fl);if(x!=JOBDB_OK)return x;jobdb_t db={0};db.path=(char*)path;db.database_id=id;db.generation=g;db.last_transaction_id=tx;db.last_checkpoint_transaction=cp;db.next_execution_id=ex;db.feature_flags=fl;jobdb_lock_t*l=NULL;x=jobdb_lock_acquire_impl(&db,db.path,5000,&l);if(x!=JOBDB_OK)return x;x=wal_recover(&db);if(x==JOBDB_OK)x=verify_records(&db);jobdb_lock_release(l);return x;}
void jobdb_close(jobdb_t *db){if(db){free(db->path);free(db);}}
jobdb_result_t jobdb_lock_acquire(jobdb_t*db,uint32_t timeout_ms,jobdb_lock_t**out){if(!db||!out)return JOBDB_ERR_INVALID_ARGUMENT;return jobdb_lock_acquire_impl(db,db->path,timeout_ms,out);}
const char *jobdb_result_string(jobdb_result_t r){switch(r){case JOBDB_OK:return "OK";case JOBDB_ERR_INVALID_ARGUMENT:return "invalid argument";case JOBDB_ERR_NOT_FOUND:return "not found";case JOBDB_ERR_ALREADY_EXISTS:return "already exists";case JOBDB_ERR_IO:return "I/O error";case JOBDB_ERR_CORRUPT:return "corrupt";case JOBDB_ERR_VERSION:return "unsupported version";case JOBDB_ERR_LIMIT:return "limit";case JOBDB_ERR_INVALID_TRANSACTION:return "invalid transaction";case JOBDB_ERR_CONFLICT:return "conflict";case JOBDB_ERR_INVALID_STATE:return "invalid state";case JOBDB_ERR_BUSY:return "busy";case JOBDB_ERR_TIMEOUT:return "timeout";case JOBDB_ERR_STALE_LEASE:return "stale lease";default:return "internal";}}
