#include "jobdb.h"
#include "jobdb_codec.h"
#include "jobdb_file.h"
#include "jobdb_lock.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#ifdef _WIN32
#include <windows.h>
#include <io.h>
#endif

#define MANIFEST_SIZE 64u
#define MANIFEST_VERSION 1u
#define WAL_VERSION 1u
#define WAL_HEADER_SIZE 48u
#define WAL_MAGIC "JOBDBWAL"
#define WAL_MAX_PAYLOAD (16u * 1024u * 1024u)
#define JOBDB_SCAN_LIMIT 4096u
#define RECORD_HEADER_SIZE 68u
#define RECORD_MAGIC "JOBDBREC"
#define EXECUTION_RECORD_TYPE 3u
#define EXECUTION_PAYLOAD_SIZE 120u
#define SCHEDULE_RECORD_TYPE 2u
#define SCHEDULE_PAYLOAD_SIZE 96u
#define STATS_RECORD_TYPE 5u
#define LEDGER_RECORD_TYPE 4u
#define STATS_PAYLOAD_SIZE 64u
#define LEDGER_PAYLOAD_SIZE 80u
static const uint8_t MAGIC[8] = {'J','O','B','D','B','M','A','N'};
struct jobdb { char *path; uint64_t database_id; uint64_t generation; uint64_t next_transaction_id; jobdb_failure_point_t failure_point; };
typedef struct tx_op { uint32_t type,target_type; uint64_t target_id,txid; uint8_t *payload; uint32_t payload_size; } tx_op_t;
struct jobdb_tx { jobdb_t *db; uint64_t id; int begun; int committed; size_t op_count; tx_op_t ops[64]; };
static jobdb_result_t wal_recover(jobdb_t *db);
static jobdb_result_t record_read(jobdb_t *db,uint32_t type,uint64_t id,jobdb_record_t*out);
static int fail_now(jobdb_t *db, jobdb_failure_point_t point);
static jobdb_result_t verify_records(jobdb_t *db){
#ifdef _WIN32
    char pattern[4096];struct _finddata_t f;intptr_t h;(void)snprintf(pattern,sizeof pattern,"%s/record.*.*",db->path);h=_findfirst(pattern,&f);if(h==-1)return JOBDB_OK;do{unsigned type=0;unsigned long long id=0;if(sscanf(f.name,"record.%u.%llu",&type,&id)==2&&type>0&&id>0){jobdb_record_t r;jobdb_result_t x=record_read(db,type,(uint64_t)id,&r);if(x!=JOBDB_OK){_findclose(h);return x;}jobdb_record_free(&r);}}while(_findnext(h,&f)==0);_findclose(h);
#else
    (void)db;
#endif
    return JOBDB_OK;
}
static jobdb_result_t tx_apply(jobdb_tx_t*tx);

static void manifest_encode(uint8_t *b, uint64_t id, uint64_t gen) {
    memset(b, 0, MANIFEST_SIZE); memcpy(b, MAGIC, 8); jobdb_put_u32le(b+8, MANIFEST_VERSION); jobdb_put_u32le(b+12, MANIFEST_SIZE);
    jobdb_put_u64le(b+16,id); jobdb_put_u64le(b+24,gen); jobdb_put_u64le(b+32,0); jobdb_put_u64le(b+40,0); jobdb_put_u64le(b+48,0); jobdb_put_u32le(b+56, jobdb_crc32c(b,56));
}
static jobdb_result_t manifest_decode(const uint8_t *b, size_t n, uint64_t *id, uint64_t *gen) {
    if (n != MANIFEST_SIZE) return JOBDB_ERR_CORRUPT;
    if (memcmp(b,MAGIC,8)!=0 || jobdb_get_u32le(b+12)!=MANIFEST_SIZE) return JOBDB_ERR_CORRUPT;
    if (jobdb_get_u32le(b+8)!=MANIFEST_VERSION) return JOBDB_ERR_VERSION;
    if (jobdb_get_u32le(b+56)!=jobdb_crc32c(b,56)) return JOBDB_ERR_CORRUPT;
    *id=jobdb_get_u64le(b+16); *gen=jobdb_get_u64le(b+24); if (*id==0) return JOBDB_ERR_CORRUPT; return JOBDB_OK;
}
static void manifest_path(char *out,size_t cap,const char *path,unsigned slot){ (void)snprintf(out,cap,"%s/manifest.%u",path,slot); }
static jobdb_result_t load_manifests(const char *path,uint64_t *id,uint64_t *gen) {
    uint64_t best_id=0,best_gen=0; int valid=0; jobdb_result_t error=JOBDB_ERR_CORRUPT;
    for(unsigned i=0;i<2;++i){ char p[4096]; uint8_t b[MANIFEST_SIZE]; size_t n=0; manifest_path(p,sizeof p,path,i); jobdb_result_t r=jobdb_read_file(p,b,sizeof b,&n); if(r!=JOBDB_OK){error=r;continue;} uint64_t x=0,g=0; r=manifest_decode(b,n,&x,&g); if(r==JOBDB_OK && (!valid || g>best_gen)){best_id=x;best_gen=g;valid=1;} else if(r==JOBDB_ERR_VERSION) error=r; }
    if(!valid)return error==JOBDB_ERR_NOT_FOUND?JOBDB_ERR_CORRUPT:error; *id=best_id;*gen=best_gen;return JOBDB_OK;
}
static char *dupstr(const char *s){ size_t n=strlen(s)+1; char *p=(char*)malloc(n); if(p)memcpy(p,s,n); return p; }
static void wal_path(char *out,size_t cap,const char *path){(void)snprintf(out,cap,"%s/wal.0",path);}
static void record_path(char *out,size_t cap,const char *path,uint32_t type,uint64_t id){(void)snprintf(out,cap,"%s/record.%u.%llu",path,(unsigned)type,(unsigned long long)id);}
static uint32_t record_crc(const uint8_t *b,uint32_t payload_size){uint8_t *x=(uint8_t*)malloc(64u+(size_t)payload_size);if(!x)return 0;memcpy(x,b,64);if(payload_size)memcpy(x+64,b+RECORD_HEADER_SIZE,payload_size);uint32_t c=jobdb_crc32c(x,64u+(size_t)payload_size);free(x);return c;}
static jobdb_result_t record_encode(const jobdb_record_t *r,uint8_t **out,size_t *out_size){
    if(!r||!out||!out_size||r->record_id==0||r->record_type==0||r->payload_size>WAL_MAX_PAYLOAD||(r->payload_size&&!r->payload))return JOBDB_ERR_INVALID_ARGUMENT;
    size_t total=RECORD_HEADER_SIZE+(size_t)r->payload_size;if(total<RECORD_HEADER_SIZE){return JOBDB_ERR_LIMIT;}uint8_t*b=(uint8_t*)calloc(1,total);if(!b)return JOBDB_ERR_INTERNAL;
    memcpy(b,RECORD_MAGIC,8);jobdb_put_u32le(b+8,r->record_type);jobdb_put_u32le(b+12,r->format_version? r->format_version:1);jobdb_put_u32le(b+16,RECORD_HEADER_SIZE);jobdb_put_u32le(b+20,(uint32_t)total);jobdb_put_u64le(b+24,r->record_id);jobdb_put_u64le(b+32,r->generation);jobdb_put_u64le(b+40,r->revision);jobdb_put_u64le(b+48,r->transaction_id);jobdb_put_u32le(b+56,r->flags);jobdb_put_u32le(b+60,r->payload_size);if(r->payload_size)memcpy(b+RECORD_HEADER_SIZE,r->payload,r->payload_size);uint32_t crc=record_crc(b,r->payload_size);if(!crc){free(b);return JOBDB_ERR_INTERNAL;}jobdb_put_u32le(b+64,crc);*out=b;*out_size=total;return JOBDB_OK;
}
static jobdb_result_t record_decode(const uint8_t*b,size_t n,jobdb_record_t*out){if(!b||!out||n<RECORD_HEADER_SIZE||memcmp(b,RECORD_MAGIC,8)!=0||jobdb_get_u32le(b+16)!=RECORD_HEADER_SIZE||jobdb_get_u32le(b+20)!=n)return JOBDB_ERR_CORRUPT;uint32_t ps=jobdb_get_u32le(b+60);if(ps>WAL_MAX_PAYLOAD||n!=RECORD_HEADER_SIZE+(size_t)ps||jobdb_get_u32le(b+64)!=record_crc(b,ps))return JOBDB_ERR_CORRUPT;memset(out,0,sizeof*out);out->record_type=jobdb_get_u32le(b+8);out->format_version=jobdb_get_u32le(b+12);out->record_id=jobdb_get_u64le(b+24);out->generation=jobdb_get_u64le(b+32);out->revision=jobdb_get_u64le(b+40);out->transaction_id=jobdb_get_u64le(b+48);out->flags=jobdb_get_u32le(b+56);out->payload_size=ps;if(ps){out->payload=(uint8_t*)malloc(ps);if(!out->payload)return JOBDB_ERR_INTERNAL;memcpy(out->payload,b+RECORD_HEADER_SIZE,ps);}return JOBDB_OK;}
static jobdb_result_t wal_append(jobdb_t *db, uint32_t type, uint64_t txid, uint32_t target_type, uint64_t target_id, const uint8_t *payload, uint32_t payload_size) {
    uint8_t *b; char path[4096]; FILE *f; size_t total;
    if(db->failure_point==JOBDB_FAILURE_DISK_FULL){db->failure_point=JOBDB_FAILURE_NONE;return JOBDB_ERR_IO;}
    if (payload_size > WAL_MAX_PAYLOAD || (payload_size != 0 && !payload)) return JOBDB_ERR_LIMIT;
    total = WAL_HEADER_SIZE + (size_t)payload_size + 4u; b=(uint8_t*)calloc(1,total); if(!b)return JOBDB_ERR_INTERNAL;
    memcpy(b,WAL_MAGIC,8); jobdb_put_u32le(b+8,WAL_VERSION); jobdb_put_u32le(b+12,type);
    jobdb_put_u64le(b+16,total); jobdb_put_u64le(b+24,txid); jobdb_put_u32le(b+32,target_type); jobdb_put_u64le(b+36,target_id); jobdb_put_u32le(b+44,payload_size);
    if(payload_size)memcpy(b+WAL_HEADER_SIZE,payload,payload_size);
    jobdb_put_u32le(b+WAL_HEADER_SIZE+payload_size,jobdb_crc32c(b,WAL_HEADER_SIZE+payload_size));
    wal_path(path,sizeof path,db->path); f=fopen(path,"ab"); if(!f){free(b);return JOBDB_ERR_IO;}
    if(fwrite(b,1,total,f)!=total || fflush(f)!=0 || fclose(f)!=0){free(b);return JOBDB_ERR_IO;} free(b); return JOBDB_OK;
}
static jobdb_result_t record_write(jobdb_t *db,const jobdb_record_t*r){uint8_t*b=NULL;size_t n=0;char p[4096],tmp[4096];if(db->failure_point==JOBDB_FAILURE_DISK_FULL){db->failure_point=JOBDB_FAILURE_NONE;return JOBDB_ERR_IO;}jobdb_result_t x=record_encode(r,&b,&n);if(x!=JOBDB_OK)return x;record_path(p,sizeof p,db->path,r->record_type,r->record_id);(void)snprintf(tmp,sizeof tmp,"%s.tmp",p);x=jobdb_write_file(tmp,b,n);free(b);if(x!=JOBDB_OK)return x;
#ifdef _WIN32
    if(!MoveFileExA(tmp,p,MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)){remove(tmp);return JOBDB_ERR_IO;}
#else
    if(rename(tmp,p)!=0){remove(tmp);return JOBDB_ERR_IO;}
#endif
    return JOBDB_OK;}
static jobdb_result_t record_read(jobdb_t*db,uint32_t type,uint64_t id,jobdb_record_t*out){char p[4096];FILE*f;long len;uint8_t*b;size_t n;record_path(p,sizeof p,db->path,type,id);f=fopen(p,"rb");if(!f)return JOBDB_ERR_NOT_FOUND;if(fseek(f,0,SEEK_END)!=0){fclose(f);return JOBDB_ERR_IO;}len=ftell(f);if(len<0||len>(long)(RECORD_HEADER_SIZE+WAL_MAX_PAYLOAD)){fclose(f);return JOBDB_ERR_CORRUPT;}if(fseek(f,0,SEEK_SET)!=0){fclose(f);return JOBDB_ERR_IO;}n=(size_t)len;b=(uint8_t*)malloc(n?n:1);if(!b){fclose(f);return JOBDB_ERR_INTERNAL;}if(fread(b,1,n,f)!=n){free(b);fclose(f);return JOBDB_ERR_IO;}fclose(f);jobdb_result_t x=record_decode(b,n,out);free(b);return x;}
static void execution_encode(const jobdb_execution_t*e,uint8_t*b){memset(b,0,EXECUTION_PAYLOAD_SIZE);jobdb_put_u64le(b,e->execution_id);jobdb_put_u64le(b+8,e->job_definition_id);jobdb_put_u64le(b+16,e->schedule_id);jobdb_put_u64le(b+24,e->workflow_id);jobdb_put_u32le(b+32,(uint32_t)e->state);jobdb_put_u64le(b+36,(uint64_t)e->created_at);jobdb_put_u64le(b+44,(uint64_t)e->eligible_at);jobdb_put_u64le(b+52,(uint64_t)e->started_at);jobdb_put_u64le(b+60,(uint64_t)e->finished_at);jobdb_put_u32le(b+68,(uint32_t)e->priority);jobdb_put_u32le(b+72,e->attempt);jobdb_put_u32le(b+76,e->max_attempts);jobdb_put_u64le(b+80,e->revision);memcpy(b+88,e->worker_instance_id,16);jobdb_put_u64le(b+104,(uint64_t)e->lease_expires_at);jobdb_put_u64le(b+112,e->fencing_token);}
static jobdb_result_t execution_decode(const jobdb_record_t*r,jobdb_execution_t*e){if(!r||!e||r->record_type!=EXECUTION_RECORD_TYPE||r->payload_size!=EXECUTION_PAYLOAD_SIZE)return JOBDB_ERR_CORRUPT;const uint8_t*b=r->payload;memset(e,0,sizeof*e);e->execution_id=jobdb_get_u64le(b);e->job_definition_id=jobdb_get_u64le(b+8);e->schedule_id=jobdb_get_u64le(b+16);e->workflow_id=jobdb_get_u64le(b+24);e->state=(jobdb_execution_state_t)jobdb_get_u32le(b+32);e->created_at=(int64_t)jobdb_get_u64le(b+36);e->eligible_at=(int64_t)jobdb_get_u64le(b+44);e->started_at=(int64_t)jobdb_get_u64le(b+52);e->finished_at=(int64_t)jobdb_get_u64le(b+60);e->priority=(int32_t)jobdb_get_u32le(b+68);e->attempt=jobdb_get_u32le(b+72);e->max_attempts=jobdb_get_u32le(b+76);e->revision=jobdb_get_u64le(b+80);memcpy(e->worker_instance_id,b+88,16);e->lease_expires_at=(int64_t)jobdb_get_u64le(b+104);e->fencing_token=jobdb_get_u64le(b+112);return e->execution_id&&e->state<12?JOBDB_OK:JOBDB_ERR_CORRUPT;}
static void schedule_encode(const jobdb_schedule_t*s,uint8_t*b){memset(b,0,SCHEDULE_PAYLOAD_SIZE);jobdb_put_u64le(b,s->schedule_id);jobdb_put_u64le(b+8,s->job_definition_id);jobdb_put_u32le(b+16,s->schedule_type);jobdb_put_u32le(b+20,s->enabled);jobdb_put_u64le(b+24,s->timezone_reference);jobdb_put_u64le(b+32,(uint64_t)s->start_at);jobdb_put_u64le(b+40,(uint64_t)s->end_at);jobdb_put_u64le(b+48,(uint64_t)s->last_fire_at);jobdb_put_u64le(b+56,(uint64_t)s->next_fire_at);jobdb_put_u64le(b+64,s->occurrence_count);jobdb_put_u64le(b+72,s->max_occurrences);jobdb_put_u32le(b+80,s->misfire_policy);jobdb_put_u32le(b+84,s->overlap_policy);jobdb_put_u64le(b+88,s->revision);}
static jobdb_result_t schedule_decode(const jobdb_record_t*r,jobdb_schedule_t*s){if(!r||!s||r->record_type!=SCHEDULE_RECORD_TYPE||r->payload_size!=SCHEDULE_PAYLOAD_SIZE)return JOBDB_ERR_CORRUPT;const uint8_t*b=r->payload;memset(s,0,sizeof*s);s->schedule_id=jobdb_get_u64le(b);s->job_definition_id=jobdb_get_u64le(b+8);s->schedule_type=jobdb_get_u32le(b+16);s->enabled=jobdb_get_u32le(b+20);s->timezone_reference=jobdb_get_u64le(b+24);s->start_at=(int64_t)jobdb_get_u64le(b+32);s->end_at=(int64_t)jobdb_get_u64le(b+40);s->last_fire_at=(int64_t)jobdb_get_u64le(b+48);s->next_fire_at=(int64_t)jobdb_get_u64le(b+56);s->occurrence_count=jobdb_get_u64le(b+64);s->max_occurrences=jobdb_get_u64le(b+72);s->misfire_policy=jobdb_get_u32le(b+80);s->overlap_policy=jobdb_get_u32le(b+84);s->revision=jobdb_get_u64le(b+88);return s->schedule_id&&s->job_definition_id?JOBDB_OK:JOBDB_ERR_CORRUPT;}
static void stats_encode(const jobdb_stats_t*s,uint8_t*b){const uint64_t v[8]={s->submitted_total,s->started_total,s->completed_total,s->failed_total,s->retried_total,s->cancelled_total,s->dead_total,s->recovered_total};memset(b,0,STATS_PAYLOAD_SIZE);for(unsigned i=0;i<8;i++)jobdb_put_u64le(b+8*i,v[i]);}
static void stats_decode(const uint8_t*b,jobdb_stats_t*s){s->submitted_total=jobdb_get_u64le(b);s->started_total=jobdb_get_u64le(b+8);s->completed_total=jobdb_get_u64le(b+16);s->failed_total=jobdb_get_u64le(b+24);s->retried_total=jobdb_get_u64le(b+32);s->cancelled_total=jobdb_get_u64le(b+40);s->dead_total=jobdb_get_u64le(b+48);s->recovered_total=jobdb_get_u64le(b+56);}
static jobdb_result_t stats_store(jobdb_t*db,const jobdb_stats_t*s){uint8_t p[STATS_PAYLOAD_SIZE];stats_encode(s,p);jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,STATS_RECORD_TYPE,1,&r);if(x==JOBDB_ERR_NOT_FOUND)return jobdb_record_create(db,STATS_RECORD_TYPE,1,p,sizeof p);if(x!=JOBDB_OK)return x;uint64_t rev=r.revision;jobdb_record_free(&r);return jobdb_record_update(db,STATS_RECORD_TYPE,1,rev,p,sizeof p,NULL);}
static jobdb_result_t stats_add_submitted(jobdb_t*db){jobdb_stats_t s;jobdb_result_t x=jobdb_get_stats(db,&s);if(x!=JOBDB_OK)return x;s.submitted_total++;return stats_store(db,&s);}
static jobdb_result_t stats_add_completed(jobdb_t*db){jobdb_stats_t s;jobdb_result_t x=jobdb_get_stats(db,&s);if(x!=JOBDB_OK)return x;s.completed_total++;return stats_store(db,&s);}
int jobdb_execution_transition_allowed(jobdb_execution_state_t from,jobdb_execution_state_t to){static const unsigned char m[12][12]={{0,1,1,0,0,0,0,0,0,0,1,1},{0,0,1,0,0,0,0,0,0,0,1,1},{0,0,0,1,0,0,0,0,0,0,1,1},{0,0,0,0,1,0,0,0,1,0,1,1},{0,0,0,0,0,1,0,1,1,0,1,0},{0,0,1,0,0,0,1,0,0,1,1,0},{0,0,1,0,0,0,0,0,0,0,1,1},{0},{0},{0},{0},{0,0,1,0,0,0,0,0,0,0,0,0}};return from<12&&to<12&&m[from][to]!=0;}
jobdb_result_t jobdb_execution_validate_transition(jobdb_execution_state_t from,jobdb_execution_state_t to){return jobdb_execution_transition_allowed(from,to)?JOBDB_OK:JOBDB_ERR_INVALID_STATE;}
jobdb_result_t jobdb_execution_create(jobdb_t*db,const jobdb_execution_t*e){if(!db||!e||!e->execution_id||e->state>=12)return JOBDB_ERR_INVALID_ARGUMENT;uint8_t p[EXECUTION_PAYLOAD_SIZE];jobdb_execution_t x=*e;x.revision=1;execution_encode(&x,p);jobdb_result_t r=jobdb_record_create(db,EXECUTION_RECORD_TYPE,e->execution_id,p,sizeof p);if(r==JOBDB_OK){jobdb_result_t sx=stats_add_submitted(db);if(sx!=JOBDB_OK)return sx;}return r;}
jobdb_result_t jobdb_execution_get(jobdb_t*db,uint64_t id,jobdb_execution_t*out){if(!db||!id||!out)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,EXECUTION_RECORD_TYPE,id,&r);if(x!=JOBDB_OK)return x;x=execution_decode(&r,out);jobdb_record_free(&r);return x;}
jobdb_result_t jobdb_execution_transition(jobdb_t*db,uint64_t id,uint64_t expected,jobdb_execution_state_t ns,uint64_t*out_revision){if(!db||!id||ns>=12)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_execution_t e;jobdb_result_t x=jobdb_execution_get(db,id,&e);if(x!=JOBDB_OK)return x;if(e.revision!=expected)return JOBDB_ERR_CONFLICT;x=jobdb_execution_validate_transition(e.state,ns);if(x!=JOBDB_OK)return x;e.state=ns;if(ns==JOBDB_EXEC_RUNNING&&e.started_at==0)e.started_at=(int64_t)time(NULL);if(ns==JOBDB_EXEC_FAILED||ns==JOBDB_EXEC_DEAD||ns==JOBDB_EXEC_CANCELLED)e.finished_at=(int64_t)time(NULL);uint8_t p[EXECUTION_PAYLOAD_SIZE];jobdb_execution_t old=e;old.revision=expected+1;execution_encode(&old,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,expected,p,sizeof p,out_revision);return x;}
static int worker_valid(const jobdb_worker_id_t*w){if(!w)return 0;for(unsigned i=0;i<16;i++)if(w->bytes[i])return 1;return 0;}
static int worker_same(const uint8_t*a,const jobdb_worker_id_t*b){return memcmp(a,b->bytes,16)==0;}
jobdb_result_t jobdb_claim_next(jobdb_t*db,const jobdb_worker_id_t*w,int64_t now,int64_t duration,jobdb_execution_t*out){if(!db||!worker_valid(w)||!out||duration<=0)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;for(uint64_t id=1;id<=JOBDB_SCAN_LIMIT;id++){jobdb_execution_t e;if(jobdb_execution_get(db,id,&e)!=JOBDB_OK)continue;if(e.state!=JOBDB_EXEC_READY||e.eligible_at>now)continue;uint64_t rev=e.revision;e.state=JOBDB_EXEC_LEASED;memcpy(e.worker_instance_id,w->bytes,16);e.lease_expires_at=now+duration;e.fencing_token++;uint8_t p[EXECUTION_PAYLOAD_SIZE];e.revision=rev+1;execution_encode(&e,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,rev,p,sizeof p,&rev);if(x==JOBDB_OK){e.revision=rev;*out=e;jobdb_lock_release(l);return JOBDB_OK;}if(x!=JOBDB_ERR_CONFLICT){jobdb_lock_release(l);return x;}}jobdb_lock_release(l);return JOBDB_ERR_NOT_FOUND;}
jobdb_result_t jobdb_renew_lease(jobdb_t*db,uint64_t id,const jobdb_worker_id_t*w,uint64_t token,int64_t expires){if(!db||!worker_valid(w)||!id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;jobdb_execution_t e;x=jobdb_execution_get(db,id,&e);if(x==JOBDB_OK&&(!worker_same(e.worker_instance_id,w)||e.fencing_token!=token||e.state!=JOBDB_EXEC_LEASED))x=JOBDB_ERR_STALE_LEASE;if(x==JOBDB_OK){e.lease_expires_at=expires;uint8_t p[EXECUTION_PAYLOAD_SIZE];uint64_t old=e.revision;e.revision=old+1;execution_encode(&e,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,old,p,sizeof p,NULL);}jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_execution_complete(jobdb_t*db,uint64_t id,const jobdb_worker_id_t*w,uint64_t token){if(!db||!worker_valid(w)||!id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;jobdb_execution_t e;x=jobdb_execution_get(db,id,&e);if(x==JOBDB_OK&&(!worker_same(e.worker_instance_id,w)||e.fencing_token!=token||e.state!=JOBDB_EXEC_RUNNING))x=JOBDB_ERR_STALE_LEASE;if(x==JOBDB_OK){e.state=JOBDB_EXEC_DONE;e.finished_at=(int64_t)time(NULL);uint8_t p[EXECUTION_PAYLOAD_SIZE];uint64_t old=e.revision;e.revision=old+1;execution_encode(&e,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,old,p,sizeof p,NULL);if(x==JOBDB_OK)x=stats_add_completed(db);}jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_execution_retry(jobdb_t*db,uint64_t id,const jobdb_worker_id_t*w,uint64_t token,int64_t eligible_at,uint64_t*out_revision){if(!db||!worker_valid(w)||!id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;jobdb_execution_t e;x=jobdb_execution_get(db,id,&e);if(x==JOBDB_OK&&(!worker_same(e.worker_instance_id,w)||e.fencing_token!=token||e.state!=JOBDB_EXEC_RUNNING))x=JOBDB_ERR_STALE_LEASE;if(x==JOBDB_OK){e.state=JOBDB_EXEC_READY;e.attempt++;e.eligible_at=eligible_at;memset(e.worker_instance_id,0,sizeof e.worker_instance_id);e.lease_expires_at=0;uint8_t p[EXECUTION_PAYLOAD_SIZE];uint64_t old=e.revision;e.revision=old+1;execution_encode(&e,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,old,p,sizeof p,out_revision);}jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_reclaim_expired(jobdb_t*db,int64_t now,uint32_t*out_count){if(!db||!out_count)return JOBDB_ERR_INVALID_ARGUMENT;*out_count=0;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;for(uint64_t id=1;id<=JOBDB_SCAN_LIMIT;id++){jobdb_execution_t e;if(jobdb_execution_get(db,id,&e)!=JOBDB_OK||e.state!=JOBDB_EXEC_LEASED||e.lease_expires_at>now)continue;uint64_t old=e.revision;e.state=JOBDB_EXEC_READY;memset(e.worker_instance_id,0,sizeof e.worker_instance_id);e.lease_expires_at=0;e.revision=old+1;uint8_t p[EXECUTION_PAYLOAD_SIZE];execution_encode(&e,p);x=jobdb_record_update(db,EXECUTION_RECORD_TYPE,id,old,p,sizeof p,NULL);if(x!=JOBDB_OK){jobdb_lock_release(l);return x;}(*out_count)++;}jobdb_lock_release(l);return JOBDB_OK;}
jobdb_result_t jobdb_schedule_create(jobdb_t*db,const jobdb_schedule_t*s){if(!db||!s||!s->schedule_id||!s->job_definition_id||s->enabled>1)return JOBDB_ERR_INVALID_ARGUMENT;uint8_t p[SCHEDULE_PAYLOAD_SIZE];jobdb_schedule_t x=*s;x.revision=1;schedule_encode(&x,p);return jobdb_record_create(db,SCHEDULE_RECORD_TYPE,s->schedule_id,p,sizeof p);}
jobdb_result_t jobdb_schedule_get(jobdb_t*db,uint64_t id,jobdb_schedule_t*out){if(!db||!id||!out)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,SCHEDULE_RECORD_TYPE,id,&r);if(x!=JOBDB_OK)return x;x=schedule_decode(&r,out);jobdb_record_free(&r);return x;}
jobdb_result_t jobdb_schedule_try_fire(jobdb_t*db,uint64_t sid,uint64_t expected,int64_t expected_next,uint64_t execution_id,int64_t fire_at,int64_t next){if(!db||!sid||!execution_id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;jobdb_schedule_t s;x=jobdb_schedule_get(db,sid,&s);if(x!=JOBDB_OK)goto done;if(!s.enabled||s.revision!=expected||s.next_fire_at!=expected_next){x=JOBDB_ERR_CONFLICT;goto done;}jobdb_execution_t e={0};e.execution_id=execution_id;e.job_definition_id=s.job_definition_id;e.schedule_id=sid;e.state=JOBDB_EXEC_READY;e.created_at=fire_at;e.eligible_at=fire_at;x=jobdb_execution_create(db,&e);if(x!=JOBDB_OK)goto done;s.last_fire_at=fire_at;s.next_fire_at=next;s.occurrence_count++;s.revision++;uint8_t p[SCHEDULE_PAYLOAD_SIZE];schedule_encode(&s,p);x=jobdb_record_update(db,SCHEDULE_RECORD_TYPE,sid,expected,p,sizeof p,NULL);done:jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_get_stats(jobdb_t*db,jobdb_stats_t*out){if(!db||!out)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,STATS_RECORD_TYPE,1,&r);if(x==JOBDB_ERR_NOT_FOUND){memset(out,0,sizeof*out);return JOBDB_OK;}if(x!=JOBDB_OK)return x;if(r.payload_size!=STATS_PAYLOAD_SIZE){jobdb_record_free(&r);return JOBDB_ERR_CORRUPT;}stats_decode(r.payload,out);jobdb_record_free(&r);return JOBDB_OK;}
static void ledger_encode(const jobdb_ledger_entry_t*e,uint8_t*b){memset(b,0,LEDGER_PAYLOAD_SIZE);jobdb_put_u64le(b,e->execution_id);jobdb_put_u64le(b+8,e->job_definition_id);jobdb_put_u64le(b+16,e->schedule_id);jobdb_put_u64le(b+24,e->workflow_id);jobdb_put_u64le(b+32,(uint64_t)e->started_at);jobdb_put_u64le(b+40,(uint64_t)e->finished_at);jobdb_put_u32le(b+48,e->attempt);jobdb_put_u32le(b+52,(uint32_t)e->final_state);jobdb_put_u64le(b+56,(uint64_t)e->duration);jobdb_put_u32le(b+64,(uint32_t)e->result_code);jobdb_put_u32le(b+68,(uint32_t)e->error_code);}
static jobdb_result_t ledger_decode(const jobdb_record_t*r,jobdb_ledger_entry_t*e){if(!r||r->payload_size!=LEDGER_PAYLOAD_SIZE)return JOBDB_ERR_CORRUPT;const uint8_t*b=r->payload;memset(e,0,sizeof*e);e->execution_id=jobdb_get_u64le(b);e->job_definition_id=jobdb_get_u64le(b+8);e->schedule_id=jobdb_get_u64le(b+16);e->workflow_id=jobdb_get_u64le(b+24);e->started_at=(int64_t)jobdb_get_u64le(b+32);e->finished_at=(int64_t)jobdb_get_u64le(b+40);e->attempt=jobdb_get_u32le(b+48);e->final_state=(jobdb_execution_state_t)jobdb_get_u32le(b+52);e->duration=(int64_t)jobdb_get_u64le(b+56);e->result_code=(int32_t)jobdb_get_u32le(b+64);e->error_code=(int32_t)jobdb_get_u32le(b+68);return e->execution_id&&e->final_state>=JOBDB_EXEC_DONE&&e->final_state<12?JOBDB_OK:JOBDB_ERR_CORRUPT;}
jobdb_result_t jobdb_ledger_append(jobdb_t*db,const jobdb_ledger_entry_t*e){if(!db||!e||!e->execution_id||e->final_state<JOBDB_EXEC_DONE||e->final_state>=12)return JOBDB_ERR_INVALID_ARGUMENT;uint8_t p[LEDGER_PAYLOAD_SIZE];ledger_encode(e,p);return jobdb_record_create(db,LEDGER_RECORD_TYPE,e->execution_id,p,sizeof p);}
jobdb_result_t jobdb_ledger_get(jobdb_t*db,uint64_t id,jobdb_ledger_entry_t*out){if(!db||!id||!out)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=jobdb_record_get(db,LEDGER_RECORD_TYPE,id,&r);if(x!=JOBDB_OK)return x;x=ledger_decode(&r,out);jobdb_record_free(&r);return x;}
typedef struct retention_item {uint64_t id,revision;int64_t finished_at;} retention_item_t;
static int retention_cmp(const void*a,const void*b){const retention_item_t*x=(const retention_item_t*)a,*y=(const retention_item_t*)b;return x->finished_at<y->finished_at?-1:x->finished_at>y->finished_at?1:0;}
jobdb_result_t jobdb_apply_retention(jobdb_t*db,int64_t now,const jobdb_retention_t*r,uint32_t*out_deleted){if(!db||!r||!out_deleted||r->max_age<0)return JOBDB_ERR_INVALID_ARGUMENT;*out_deleted=0;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;retention_item_t*items=(retention_item_t*)calloc(JOBDB_SCAN_LIMIT,sizeof*items);if(!items){jobdb_lock_release(l);return JOBDB_ERR_INTERNAL;}size_t count=0;for(uint64_t id=1;id<=JOBDB_SCAN_LIMIT;id++){jobdb_record_t rec;if(jobdb_record_get(db,LEDGER_RECORD_TYPE,id,&rec)!=JOBDB_OK)continue;jobdb_ledger_entry_t e;if(ledger_decode(&rec,&e)==JOBDB_OK&&count<JOBDB_SCAN_LIMIT){items[count].id=id;items[count].revision=rec.revision;items[count].finished_at=e.finished_at;count++;}jobdb_record_free(&rec);}qsort(items,count,sizeof*items,retention_cmp);uint64_t keep=count;for(size_t i=0;i<count;i++){int expired=r->max_age>0&&items[i].finished_at>0&&items[i].finished_at<=now-r->max_age;if(expired||((r->max_records>0&&keep>r->max_records))||(r->max_bytes>0&&keep* (uint64_t)(RECORD_HEADER_SIZE+LEDGER_PAYLOAD_SIZE)>r->max_bytes)){jobdb_record_delete(db,LEDGER_RECORD_TYPE,items[i].id,items[i].revision);if(keep)keep--;(*out_deleted)++;}}free(items);jobdb_lock_release(l);return JOBDB_OK;}
jobdb_result_t jobdb_checkpoint(jobdb_t*db){if(!db)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_lock_t*l=NULL;jobdb_result_t x=jobdb_lock_acquire(db,0,&l);if(x!=JOBDB_OK)return x;x=wal_recover(db);if(x!=JOBDB_OK){jobdb_lock_release(l);return x;}if(fail_now(db,JOBDB_FAILURE_CHECKPOINT_BEFORE_MANIFEST)){jobdb_lock_release(l);return JOBDB_ERR_IO;}uint8_t b[MANIFEST_SIZE];char p[4096];uint64_t next=db->generation+1;manifest_encode(b,db->database_id,next);manifest_path(p,sizeof p,db->path,(unsigned)(next&1u));x=jobdb_write_file(p,b,sizeof b);if(x==JOBDB_OK)db->generation=next;if(x==JOBDB_OK&&fail_now(db,JOBDB_FAILURE_CHECKPOINT_AFTER_MANIFEST))x=JOBDB_ERR_IO;jobdb_lock_release(l);return x;}
jobdb_result_t jobdb_list_record_ids(jobdb_t*db,uint32_t type,uint64_t*ids,size_t capacity,size_t*out_count){if(!db||!type||!out_count||(capacity&&!ids))return JOBDB_ERR_INVALID_ARGUMENT;*out_count=0;for(uint64_t id=1;id<=JOBDB_SCAN_LIMIT;id++){jobdb_record_t r;if(jobdb_record_get(db,type,id,&r)!=JOBDB_OK)continue;jobdb_record_free(&r);if(*out_count<capacity)ids[*out_count]=id;(*out_count)++;}return JOBDB_OK;}
void jobdb_record_free(jobdb_record_t*r){if(r){free(r->payload);memset(r,0,sizeof*r);}}
jobdb_result_t jobdb_record_create(jobdb_t*db,uint32_t type,uint64_t id,const void*payload,uint32_t size){if(!db||!type||!id||(size&&!payload)||size>WAL_MAX_PAYLOAD)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t old;jobdb_result_t x=record_read(db,type,id,&old);if(x==JOBDB_OK){jobdb_record_free(&old);return JOBDB_ERR_ALREADY_EXISTS;}if(x!=JOBDB_ERR_NOT_FOUND)return x;jobdb_record_t r={type,1,id,db->generation,1,0,0,(uint8_t*)payload,size};return record_write(db,&r);}
jobdb_result_t jobdb_record_get(jobdb_t*db,uint32_t type,uint64_t id,jobdb_record_t*out){if(!db||!out||!type||!id)return JOBDB_ERR_INVALID_ARGUMENT;return record_read(db,type,id,out);}
jobdb_result_t jobdb_record_update(jobdb_t*db,uint32_t type,uint64_t id,uint64_t expected,const void*payload,uint32_t size,uint64_t*out_revision){if(!db||!type||!id||(size&&!payload)||size>WAL_MAX_PAYLOAD)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=record_read(db,type,id,&r);if(x!=JOBDB_OK)return x;if(r.revision!=expected){jobdb_record_free(&r);return JOBDB_ERR_CONFLICT;}r.revision++;r.generation=db->generation;r.payload=(uint8_t*)payload;r.payload_size=size;x=record_write(db,&r);r.payload=NULL;jobdb_record_free(&r);if(x==JOBDB_OK&&out_revision)*out_revision=expected+1;return x;}
jobdb_result_t jobdb_record_delete(jobdb_t*db,uint32_t type,uint64_t id,uint64_t expected){if(!db||!type||!id)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_record_t r;jobdb_result_t x=record_read(db,type,id,&r);if(x!=JOBDB_OK)return x;if(r.revision!=expected){jobdb_record_free(&r);return JOBDB_ERR_CONFLICT;}char p[4096];record_path(p,sizeof p,db->path,type,id);jobdb_record_free(&r);return remove(p)==0?JOBDB_OK:JOBDB_ERR_IO;}
static int fail_now(jobdb_t *db, jobdb_failure_point_t point){if(db->failure_point==point){db->failure_point=JOBDB_FAILURE_NONE;return 1;}return 0;}
static jobdb_result_t wal_recover(jobdb_t *db) {
    char path[4096]; FILE *f; uint8_t h[WAL_HEADER_SIZE]; uint8_t *payload=NULL; size_t n; uint64_t max_id=0;tx_op_t ops[1024];size_t op_count=0;uint64_t committed[1024];size_t committed_count=0;memset(ops,0,sizeof ops);
    wal_path(path,sizeof path,db->path); f=fopen(path,"rb"); if(!f){return errno==ENOENT?JOBDB_OK:JOBDB_ERR_IO;}
    for(;;){ n=fread(h,1,sizeof h,f); if(n==0)break; if(n!=sizeof h){jobdb_result_t r=(n<8 || memcmp(h,WAL_MAGIC,n<8?n:8)!=0)?JOBDB_ERR_CORRUPT:JOBDB_OK;fclose(f);return r;}
        uint64_t record_size=jobdb_get_u64le(h+16); uint32_t payload_size=jobdb_get_u32le(h+44);
        if(memcmp(h,WAL_MAGIC,8)!=0 || jobdb_get_u32le(h+8)!=WAL_VERSION || jobdb_get_u32le(h+12)<1 || jobdb_get_u32le(h+12)>4 || record_size != WAL_HEADER_SIZE+(uint64_t)payload_size+4u || payload_size>WAL_MAX_PAYLOAD || jobdb_get_u64le(h+24)==0){fclose(f);free(payload);return JOBDB_ERR_CORRUPT;}
        free(payload); payload=NULL; if(payload_size){payload=(uint8_t*)malloc(payload_size);if(!payload){fclose(f);return JOBDB_ERR_INTERNAL;} n=fread(payload,1,payload_size,f);if(n!=payload_size){free(payload);fclose(f);return memcmp(h,WAL_MAGIC,8)==0?JOBDB_OK:JOBDB_ERR_CORRUPT;}}
        uint8_t c[4]; n=fread(c,1,4,f); if(n!=4){free(payload);fclose(f);return JOBDB_OK;}
        uint8_t *check=(uint8_t*)malloc(WAL_HEADER_SIZE+payload_size);if(!check){free(payload);fclose(f);return JOBDB_ERR_INTERNAL;}memcpy(check,h,WAL_HEADER_SIZE);if(payload_size)memcpy(check+WAL_HEADER_SIZE,payload,payload_size);uint32_t expected=jobdb_crc32c(check,WAL_HEADER_SIZE+payload_size);free(check);if(jobdb_get_u32le(c)!=expected){free(payload);fclose(f);return JOBDB_ERR_CORRUPT;}
        if(jobdb_get_u64le(h+24)>max_id)max_id=jobdb_get_u64le(h+24);
        uint32_t type=jobdb_get_u32le(h+12);uint64_t txid=jobdb_get_u64le(h+24);
        if(type==2||type==3){if(op_count>=1024){free(payload);fclose(f);return JOBDB_ERR_LIMIT;}ops[op_count].type=type;ops[op_count].target_type=jobdb_get_u32le(h+32);ops[op_count].target_id=jobdb_get_u64le(h+36);ops[op_count].txid=txid;ops[op_count].payload_size=payload_size;if(payload_size){ops[op_count].payload=(uint8_t*)malloc(payload_size);if(!ops[op_count].payload){free(payload);fclose(f);return JOBDB_ERR_INTERNAL;}memcpy(ops[op_count].payload,payload,payload_size);}op_count++;}else if(type==4){if(committed_count>=1024){free(payload);fclose(f);return JOBDB_ERR_LIMIT;}committed[committed_count++]=txid;}
    }
    free(payload); fclose(f); if(max_id>=db->next_transaction_id)db->next_transaction_id=max_id+1;for(size_t i=0;i<op_count;i++){int is_committed=0;for(size_t j=0;j<committed_count;j++)if(ops[i].txid==committed[j]){is_committed=1;break;}if(is_committed){jobdb_tx_t fake={0};fake.db=db;fake.id=ops[i].txid;fake.op_count=1;fake.ops[0]=ops[i];if(tx_apply(&fake)!=JOBDB_OK){for(size_t k=0;k<op_count;k++)free(ops[k].payload);return JOBDB_ERR_IO;}ops[i].payload=NULL;}}for(size_t i=0;i<op_count;i++)free(ops[i].payload);return JOBDB_OK;
}
jobdb_result_t jobdb_create(const char *path, jobdb_t **out_db){
    if(!path||!out_db||!*path){return JOBDB_ERR_INVALID_ARGUMENT;} *out_db=NULL; jobdb_result_t r=jobdb_make_dir(path); if(r!=JOBDB_OK&&r!=JOBDB_ERR_ALREADY_EXISTS)return r;
    char p[4096]; uint8_t b[MANIFEST_SIZE]; uint64_t id=0x9e3779b97f4a7c15ULL; if(r==JOBDB_ERR_ALREADY_EXISTS){char m0[4096],m1[4096];manifest_path(m0,sizeof m0,path,0);manifest_path(m1,sizeof m1,path,1);if(jobdb_file_exists(m0)||jobdb_file_exists(m1))return JOBDB_ERR_ALREADY_EXISTS;} manifest_encode(b,id,1); manifest_path(p,sizeof p,path,0); r=jobdb_write_file(p,b,sizeof b); if(r!=JOBDB_OK)return r; manifest_encode(b,id,2); manifest_path(p,sizeof p,path,1); r=jobdb_write_file(p,b,sizeof b); if(r!=JOBDB_OK)return r;
    jobdb_t *db=(jobdb_t*)calloc(1,sizeof *db); if(!db)return JOBDB_ERR_INTERNAL; db->path=dupstr(path); if(!db->path){free(db);return JOBDB_ERR_INTERNAL;}db->database_id=id;db->generation=2;db->next_transaction_id=1;*out_db=db;return JOBDB_OK;
}
jobdb_result_t jobdb_open(const char *path, jobdb_t **out_db){ if(!path||!out_db||!*path)return JOBDB_ERR_INVALID_ARGUMENT;*out_db=NULL;uint64_t id=0,g=0;jobdb_result_t r=load_manifests(path,&id,&g);if(r!=JOBDB_OK)return r;jobdb_t*db=(jobdb_t*)calloc(1,sizeof*db);if(!db)return JOBDB_ERR_INTERNAL;db->path=dupstr(path);if(!db->path){free(db);return JOBDB_ERR_INTERNAL;}db->database_id=id;db->generation=g;db->next_transaction_id=1;r=wal_recover(db);if(r!=JOBDB_OK){jobdb_close(db);return r;}*out_db=db;return JOBDB_OK; }
jobdb_result_t jobdb_tx_begin(jobdb_t *db, jobdb_tx_t **out_tx){if(!db||!out_tx)return JOBDB_ERR_INVALID_ARGUMENT;*out_tx=NULL;jobdb_tx_t*tx=(jobdb_tx_t*)calloc(1,sizeof*tx);if(!tx)return JOBDB_ERR_INTERNAL;tx->db=db;tx->id=db->next_transaction_id++;tx->begun=1;jobdb_result_t r=wal_append(db,1,tx->id,0,0,NULL,0);if(r!=JOBDB_OK){free(tx);return r;}if(fail_now(db,JOBDB_FAILURE_AFTER_BEGIN)){free(tx);return JOBDB_ERR_IO;}*out_tx=tx;return JOBDB_OK;}
jobdb_result_t jobdb_tx_put(jobdb_tx_t *tx,uint32_t target_type,uint64_t target_id,const void *payload,uint32_t payload_size){if(!tx||!tx->begun||tx->committed||target_id==0||tx->op_count>=64)return JOBDB_ERR_INVALID_TRANSACTION;jobdb_result_t r=wal_append(tx->db,2,tx->id,target_type,target_id,(const uint8_t*)payload,payload_size);if(r!=JOBDB_OK)return r;tx_op_t*op=&tx->ops[tx->op_count++];op->type=2;op->target_type=target_type;op->target_id=target_id;op->payload_size=payload_size;if(payload_size){op->payload=(uint8_t*)malloc(payload_size);if(!op->payload)return JOBDB_ERR_INTERNAL;memcpy(op->payload,payload,payload_size);}if(fail_now(tx->db,JOBDB_FAILURE_AFTER_OPERATION))return JOBDB_ERR_IO;return JOBDB_OK;}
jobdb_result_t jobdb_tx_delete(jobdb_tx_t *tx,uint32_t target_type,uint64_t target_id){if(!tx||!tx->begun||tx->committed||target_id==0||tx->op_count>=64)return JOBDB_ERR_INVALID_TRANSACTION;jobdb_result_t r=wal_append(tx->db,3,tx->id,target_type,target_id,NULL,0);if(r==JOBDB_OK){tx->ops[tx->op_count].type=3;tx->ops[tx->op_count].target_type=target_type;tx->ops[tx->op_count].target_id=target_id;tx->op_count++;}if(r==JOBDB_OK&&fail_now(tx->db,JOBDB_FAILURE_AFTER_OPERATION))return JOBDB_ERR_IO;return r;}
static jobdb_result_t tx_apply(jobdb_tx_t*tx){for(size_t i=0;i<tx->op_count;i++){tx_op_t*op=&tx->ops[i];char p[4096];record_path(p,sizeof p,tx->db->path,op->target_type,op->target_id);if(op->type==3){if(remove(p)!=0&&errno!=ENOENT)return JOBDB_ERR_IO;continue;}jobdb_record_t old;uint64_t rev=1;jobdb_result_t r=record_read(tx->db,op->target_type,op->target_id,&old);if(r==JOBDB_OK){if(old.transaction_id==tx->id&&old.payload_size==op->payload_size&&(!op->payload_size||memcmp(old.payload,op->payload,op->payload_size)==0)){jobdb_record_free(&old);continue;}rev=old.revision+1;jobdb_record_free(&old);}else if(r!=JOBDB_ERR_NOT_FOUND)return r;jobdb_record_t rec={op->target_type,1,op->target_id,tx->db->generation,rev,tx->id,0,op->payload,op->payload_size};r=record_write(tx->db,&rec);if(r!=JOBDB_OK)return r;}return JOBDB_OK;}
jobdb_result_t jobdb_tx_commit(jobdb_tx_t *tx){if(!tx||!tx->begun||tx->committed)return JOBDB_ERR_INVALID_TRANSACTION;if(fail_now(tx->db,JOBDB_FAILURE_BEFORE_COMMIT))return JOBDB_ERR_IO;jobdb_result_t r=wal_append(tx->db,4,tx->id,0,0,NULL,0);if(r==JOBDB_OK)tx->committed=1;if(r==JOBDB_OK&&fail_now(tx->db,JOBDB_FAILURE_AFTER_COMMIT))return JOBDB_ERR_IO;if(r==JOBDB_OK)r=tx_apply(tx);return r;}
void jobdb_tx_rollback(jobdb_tx_t *tx){if(tx){for(size_t i=0;i<tx->op_count;i++)free(tx->ops[i].payload);free(tx);}}
void jobdb_test_fail_next(jobdb_t *db, jobdb_failure_point_t point){if(db)db->failure_point=point;}
jobdb_result_t jobdb_verify(const char *path){uint64_t id=0,g=0;if(!path)return JOBDB_ERR_INVALID_ARGUMENT;jobdb_result_t x=load_manifests(path,&id,&g);if(x!=JOBDB_OK)return x;jobdb_t db={0};db.path=(char*)path;db.database_id=id;db.generation=g;db.next_transaction_id=1;x=wal_recover(&db);if(x!=JOBDB_OK)return x;return verify_records(&db);}
void jobdb_close(jobdb_t *db){if(db){free(db->path);free(db);}}
jobdb_result_t jobdb_lock_acquire(jobdb_t*db,uint32_t timeout_ms,jobdb_lock_t**out){if(!db||!out)return JOBDB_ERR_INVALID_ARGUMENT;return jobdb_lock_acquire_impl(db,db->path,timeout_ms,out);}
const char *jobdb_result_string(jobdb_result_t r){switch(r){case JOBDB_OK:return "OK";case JOBDB_ERR_INVALID_ARGUMENT:return "invalid argument";case JOBDB_ERR_NOT_FOUND:return "not found";case JOBDB_ERR_ALREADY_EXISTS:return "already exists";case JOBDB_ERR_IO:return "I/O error";case JOBDB_ERR_CORRUPT:return "corrupt";case JOBDB_ERR_VERSION:return "unsupported version";case JOBDB_ERR_LIMIT:return "limit";case JOBDB_ERR_INVALID_TRANSACTION:return "invalid transaction";case JOBDB_ERR_CONFLICT:return "conflict";case JOBDB_ERR_INVALID_STATE:return "invalid state";case JOBDB_ERR_BUSY:return "busy";case JOBDB_ERR_TIMEOUT:return "timeout";case JOBDB_ERR_STALE_LEASE:return "stale lease";default:return "internal";}}
